apiVersion: v1
kind: Service
metadata:
  name: tenant-svc
  namespace: zoiko-identity
  labels:
    app: tenant-svc
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  selector:
    app: tenant-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenant-svc
  namespace: zoiko-identity
  labels:
    app: tenant-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-svc
  template:
    metadata:
      labels:
        app: tenant-svc
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
      containers:
      - name: tenant-svc
        image: tenant-svc:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: PORT
          value: "8081"
        - name: DB_HOST
          value: "postgres.zoiko-infra.svc.cluster.local"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "tenant_entity_registry"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: DB_SSLMODE
          value: "disable"
        - name: KAFKA_BROKERS
          value: "kafka.zoiko-infra.svc.cluster.local:9092"
        - name: KAFKA_GROUP_ID
          value: "tenant-entity-registry-svc"
        - name: KAFKA_EVENTS_TOPIC
          value: "zoiko.entity.events"
        - name: JURISDICTION_RULES_URL
          value: "http://jurisdiction-svc.zoiko-governance.svc.cluster.local:8082"
        - name: AUTHZ_SERVICE_URL
          value: "http://tenant-svc.zoiko-identity.svc.cluster.local:8081"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
