#!/usr/bin/env bash
# Concatenate a RANGE of migrations into one file you can paste into the
# Supabase SQL editor, for a database that already has the earlier ones.
#
#   ./build-delta.sh 0022 0025   →  writes zoiko-suite-0022-0025.sql
#   ./build-delta.sh 0022        →  0022 to the end
#
# build-combined.sh writes the WHOLE set, which is what a fresh project needs.
# It cannot be re-run against a database that already has some of it: the
# per-service files use bare CREATE TABLE, so the first already-existing table
# aborts the batch. Deliberately bare rather than IF NOT EXISTS — a table that
# exists with a DIFFERENT shape must fail loudly, not be silently skipped and
# leave the schema half-migrated.
#
# So adding services to a live project means pasting only the new files, in
# order. This produces exactly that.
#
# Bounds are matched against the four-digit prefix, inclusive of both ends.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

FROM="${1:-}"
TO="${2:-9999}"

if [ -z "$FROM" ]; then
    echo "usage: $(basename "$0") <from-prefix> [to-prefix]" >&2
    echo "   e.g. $(basename "$0") 0022 0025" >&2
    exit 2
fi

OUT="$HERE/zoiko-suite-$FROM-$TO.sql"
if [ "$TO" = 9999 ]; then
    OUT="$HERE/zoiko-suite-$FROM-onwards.sql"
fi

shopt -s nullglob
selected=()
for f in "$HERE"/migrations/*.sql; do
    base="$(basename "$f")"
    prefix="${base%%_*}"
    # String compare is safe because every prefix is exactly four digits.
    if [[ "$prefix" > "$FROM" || "$prefix" == "$FROM" ]] \
    && [[ "$prefix" < "$TO"   || "$prefix" == "$TO"   ]]; then
        selected+=("$f")
    fi
done

if [ ${#selected[@]} -eq 0 ]; then
    echo "no migrations in range $FROM..$TO" >&2
    exit 1
fi

{
    cat <<HEADER
-- ============================================================================
-- Zoiko Suite — Supabase migrations $FROM to $TO.
--
-- Generated by supabase/build-delta.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- A DELTA, for a project that already has the earlier migrations applied.
-- For a fresh project use zoiko-suite-all.sql instead — this file assumes
-- 0001_platform_foundation has already created:
--
--   - the zoiko_backend role
--   - the app schema, app.current_tenant_id() and app.current_principal_id()
--
-- Verify what is already applied before pasting this:
--
--   SELECT nspname FROM pg_namespace
--    WHERE nspname NOT LIKE 'pg_%'
--      AND nspname NOT IN ('information_schema','public')
--    ORDER BY 1;
--
-- Every CREATE below is bare, not IF NOT EXISTS, on purpose: if something here
-- already exists the batch must abort so you can look at why, rather than skip
-- it and leave the schema half-migrated.
-- ============================================================================

HEADER

    for f in "${selected[@]}"; do
        printf '\n\n-- %s\n' "$(printf '=%.0s' {1..76})"
        printf -- '-- FILE: %s\n' "$(basename "$f")"
        printf -- '-- %s\n\n' "$(printf '=%.0s' {1..76})"
        cat "$f"
    done
} > "$OUT"

echo "wrote $OUT"
echo "  ${#selected[@]} migration(s): $(for f in "${selected[@]}"; do printf '%s ' "$(basename "$f")"; done)"
echo "  $(grep -ciE '^\s*CREATE TABLE' "$OUT") tables, $(grep -ciE '^\s*CREATE SCHEMA' "$OUT") schemas"
