#!/usr/bin/env bash
# Concatenate every migration, in order, into one file you can paste into the
# Supabase SQL editor in a single go.
#
#   ./build-combined.sh   →  writes zoiko-suite-all.sql
#
# Regenerate rather than hand-edit: the per-service files under migrations/ are
# the source of truth, and this output is derived from them.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/zoiko-suite-all.sql"

{
    cat <<'HEADER'
-- ============================================================================
-- Zoiko Suite — complete Supabase schema for the 20 finished services.
--
-- Generated by supabase/build-combined.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- Creates 21 schemas (`app` plus one per service) and 42 tables. Safe to run
-- as a single statement batch in the Supabase SQL editor.
--
-- BEFORE YOU RUN THIS, and BEFORE any service connects:
--
--   1. Rotate the zoiko_backend password. The foundation section creates the
--      role with a placeholder:
--        ALTER ROLE zoiko_backend WITH PASSWORD '<from your secret manager>';
--
--   2. Point the Go services at zoiko_backend, NOT at the postgres user and
--      NOT at the service_role key. Both bypass row-level security, which
--      would reproduce the exact gap this migration exists to close: on the
--      compose estate every service connects as the superuser, so all 119 RLS
--      policies are present, correct, and have never executed.
--
--   3. Expose the schemas you want reachable through PostgREST in your
--      project's API settings. `secret_vault_integration` deliberately grants
--      the `authenticated` role nothing and should not be exposed at all.
-- ============================================================================

HEADER

    for f in "$HERE"/migrations/*.sql; do
        printf '\n\n-- %s\n' "$(printf '=%.0s' {1..76})"
        printf -- '-- FILE: %s\n' "$(basename "$f")"
        printf -- '-- %s\n\n' "$(printf '=%.0s' {1..76})"
        cat "$f"
    done
} > "$OUT"

echo "wrote $OUT"
echo "  $(grep -c . "$OUT") non-blank lines, $(wc -c < "$OUT") bytes"
echo "  $(grep -ciE '^\s*CREATE TABLE' "$OUT") tables, $(grep -ciE '^\s*CREATE SCHEMA' "$OUT") schemas"
