-- ============================================================================
-- Zoiko Suite — Supabase migrations 0033 to 0033.
--
-- Generated by supabase/build-delta.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- A DELTA, for a project that already has the earlier migrations applied.
-- For a fresh project use zoiko-suite-all.sql instead — this file assumes
-- 0001_platform_foundation has already created:
--
--   - the zoiko_backend role
--   - the app schema, app.current_tenant_id() and app.current_principal_id()
--
-- Verify what is already applied before pasting this:
--
--   SELECT nspname FROM pg_namespace
--    WHERE nspname NOT LIKE 'pg_%'
--      AND nspname NOT IN ('information_schema','public')
--    ORDER BY 1;
--
-- Every CREATE below is bare, not IF NOT EXISTS, on purpose: if something here
-- already exists the batch must abort so you can look at why, rather than skip
-- it and leave the schema half-migrated.
-- ============================================================================



-- ============================================================================
-- FILE: 0033_notification_delivery_retry.sql
-- ============================================================================

-- 0033_notification_delivery_retry.sql
-- notification-svc → schema `notification`. Creates no tables.
--
-- The change notification-svc's own 000004_delivery_retry makes, in the form
-- this project applies it. Same statements, same end state; whichever runs
-- first, the other is a no-op.
--
-- ── What this closes ────────────────────────────────────────────────────────
--
-- 0032 gave the register somewhere to record that a delivery failure was worth
-- re-attempting, and nothing re-attempted it. A greylisted payslip notice, a
-- relay restarting, an identity-context-svc blip: each concluded FAILED on the
-- first try and stayed that way. The classification existed and was inert.
--
-- No new status value. PENDING already means "delivery has not concluded", and
-- a notification awaiting another attempt has not concluded:
--
--   PENDING, next_attempt_at IS NOT NULL  → will be attempted again
--   PENDING, next_attempt_at IS NULL      → in flight right now
--   SENT                                  → a provider accepted it
--   FAILED                                → terminal; no further attempt
--
-- A RETRYING status would have meant widening the status vocabulary, updating
-- every consumer, and leaving FAILED ambiguous for the length of the rollout.

DO $guard$
BEGIN

IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'notification') THEN
    RAISE NOTICE 'schema notification absent; skipping 0033 — re-run it after 0007 has created the schema';
    RETURN;
END IF;

EXECUTE $stmt$ALTER TABLE notification.notifications ADD COLUMN IF NOT EXISTS delivery_attempts INT NOT NULL DEFAULT 0$stmt$;
EXECUTE $stmt$ALTER TABLE notification.notifications ADD COLUMN IF NOT EXISTS next_attempt_at TIMESTAMPTZ$stmt$;
EXECUTE $stmt$ALTER TABLE notification.notifications ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ$stmt$;

-- A concluded notification must not be scheduled for another attempt. Without
-- this, a bug that forgot to clear next_attempt_at on success would have the
-- worker re-sending a message already delivered — the duplicate-notice failure
-- ZS-SVC-Y-001 §0.4 names directly.
IF NOT EXISTS (SELECT 1 FROM pg_constraint
                WHERE conname = 'notifications_concluded_has_no_retry'
                  AND conrelid = 'notification.notifications'::regclass) THEN
    EXECUTE $stmt$
    ALTER TABLE notification.notifications
        ADD CONSTRAINT notifications_concluded_has_no_retry
        CHECK (status = 'PENDING' OR next_attempt_at IS NULL) NOT VALID
    $stmt$;
END IF;

IF NOT EXISTS (SELECT 1 FROM pg_constraint
                WHERE conname = 'notifications_attempts_non_negative'
                  AND conrelid = 'notification.notifications'::regclass) THEN
    EXECUTE $stmt$
    ALTER TABLE notification.notifications
        ADD CONSTRAINT notifications_attempts_non_negative
        CHECK (delivery_attempts >= 0) NOT VALID
    $stmt$;
END IF;

-- The worker's claim query, and only that. Partial because due retries are a
-- vanishingly small slice of a register that only grows.
EXECUTE $stmt$
CREATE INDEX IF NOT EXISTS idx_notifications_due_retry
    ON notification.notifications (next_attempt_at)
    WHERE next_attempt_at IS NOT NULL AND status = 'PENDING'
$stmt$;

-- ── The cross-tenant problem, and why this is the narrowest answer ──────────
--
-- The retry worker is not serving a request. Nobody's tenant is installed on
-- its connection, and this table is ENABLE + FORCE with a policy keyed on the
-- caller's tenant — so the worker, correctly, sees nothing, and cannot even
-- discover which tenants have work waiting.
--
-- This is the platform-scope hatch 0028 documents on authorization_svc.roles,
-- in its narrowest form:
--
--   FOR SELECT ONLY. A platform-scoped connection can DISCOVER work. It cannot
--   insert, update or delete across tenants — every write still requires the
--   correct tenant, so the retry itself runs tenant-scoped like any request.
--
-- RLS cannot restrict columns, so a connection setting this flag can read
-- message bodies. What bounds that is the caller: the worker's claim query
-- projects notification_id and tenant_id and nothing else, then drops platform
-- scope and re-enters per tenant to read the message. No content crosses it.
--
-- set_config(..., true) is transaction-local, so the flag cannot survive on a
-- pooled connection into somebody's request.
--
-- current_setting directly rather than an app.* helper: there is no
-- app.platform_scope() function, and 0028 reads the setting the same way.
--
-- NO `TO` CLAUSE, and that is not an oversight.
--
-- 0007 wrote this table's policies `TO zoiko_backend`, and the first draft of
-- this migration copied that. It would have been inert. Services do not
-- connect as zoiko_backend: deployments/supabase creates a role per service
-- (app_notification here) and REVOKEs zoiko_backend membership from it
-- deliberately, because that role accumulates DML on every schema and a member
-- would inherit the lot — 0026 measured app_employee_master reading and
-- writing payroll_run.pay_slips through exactly that membership.
--
-- 0026's fix was to drop the role restriction platform-wide so policies apply
-- to whichever role actually connects. A `TO zoiko_backend` policy here would
-- therefore match nobody, the worker's claim query would return zero rows
-- forever, and retry would appear to work while silently never firing.
--
-- Widening to PUBLIC costs nothing that is not already the case: table
-- privileges are checked BEFORE row security, `anon` is granted nothing on
-- this table and never reaches a policy, and `authenticated` already reads its
-- tenant's rows through tenant_isolation. What this policy adds for
-- `authenticated` is gated behind app.platform_scope, a GUC PostgREST gives a
-- client no way to set — it sets only request.* and the role.
--
-- The verification block asserts the ABSENCE of a role restriction, because
-- re-adding one is the change that would break the worker quietly.
EXECUTE $stmt$DROP POLICY IF EXISTS platform_scope_read_policy ON notification.notifications$stmt$;
EXECUTE $stmt$DROP POLICY IF EXISTS platform_scope_read ON notification.notifications$stmt$;
EXECUTE $stmt$
CREATE POLICY platform_scope_read ON notification.notifications
    FOR SELECT
    USING (current_setting('app.platform_scope', true) = 'true')
$stmt$;

-- ── Verification ────────────────────────────────────────────────────────────

DECLARE missing text; polcount int;
BEGIN
    SELECT string_agg(c.col, ', ')
      INTO missing
      FROM (VALUES ('delivery_attempts'), ('next_attempt_at'), ('last_attempt_at')) AS c(col)
     WHERE NOT EXISTS (
        SELECT 1 FROM information_schema.columns
         WHERE table_schema = 'notification'
           AND table_name   = 'notifications'
           AND column_name  = c.col);

    IF missing IS NOT NULL THEN
        RAISE EXCEPTION '0033 did not add: %', missing;
    END IF;

    -- Both of 0007's policies must survive. tenant_isolation is what scopes
    -- the backend to one tenant; recipient_read is what stops an authenticated
    -- caller reading a colleague's notification body. A platform-scope policy
    -- that replaced either would read as a working retry worker and be a loss
    -- of exactly the isolation this table is careful about.
    --
    -- Named `tenant_isolation`, not `tenant_isolation_policy`: this project
    -- uses the former (49 tables), the compose migrations use the latter. The
    -- first version of this check looked for the compose name and failed here
    -- on a correctly-migrated database — the check was wrong, not the schema.
    SELECT count(*) INTO polcount
      FROM pg_policies
     WHERE schemaname = 'notification' AND tablename = 'notifications'
       AND policyname IN ('tenant_isolation', 'recipient_read');
    IF polcount <> 2 THEN
        RAISE EXCEPTION
            'expected both tenant_isolation and recipient_read on notification.notifications, found % — '
            'the platform-scope policy must sit ALONGSIDE them, never replace them', polcount;
    END IF;

    -- The hatch must be SELECT-only...
    IF EXISTS (
        SELECT 1 FROM pg_policies
         WHERE schemaname = 'notification' AND tablename = 'notifications'
           AND policyname = 'platform_scope_read'
           AND cmd <> 'SELECT') THEN
        RAISE EXCEPTION 'platform_scope_read is not SELECT-only — it would permit cross-tenant writes';
    END IF;

    -- ...and must NOT be restricted to a role.
    --
    -- The inverse of the usual check, for the reason 0026 exists: services
    -- connect as app_notification, which is deliberately not a member of
    -- zoiko_backend. A role-restricted policy here would match nobody, the
    -- worker's claim query would return zero rows forever, and the retry
    -- machinery would look present while never firing — the worst kind of
    -- failure, because nothing errors.
    SELECT count(*) INTO polcount
      FROM pg_policies
     WHERE schemaname = 'notification' AND tablename = 'notifications'
       AND policyname = 'platform_scope_read'
       AND roles = '{public}';
    IF polcount <> 1 THEN
        RAISE EXCEPTION
            'platform_scope_read is role-restricted — it must apply to the connecting role '
            '(0026), or the retry worker silently sees nothing';
    END IF;

    RAISE NOTICE 'verified: 0033 applied — retry scheduling present, both 0007 policies intact, hatch is read-only and applies to the connecting role';
END;

END
$guard$;
