-- ============================================================================
-- Zoiko Suite — Supabase migrations 0031 to 0031.
--
-- Generated by supabase/build-delta.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- A DELTA, for a project that already has the earlier migrations applied.
-- For a fresh project use zoiko-suite-all.sql instead — this file assumes
-- 0001_platform_foundation has already created:
--
--   - the zoiko_backend role
--   - the app schema, app.current_tenant_id() and app.current_principal_id()
--
-- Verify what is already applied before pasting this:
--
--   SELECT nspname FROM pg_namespace
--    WHERE nspname NOT LIKE 'pg_%'
--      AND nspname NOT IN ('information_schema','public')
--    ORDER BY 1;
--
-- Every CREATE below is bare, not IF NOT EXISTS, on purpose: if something here
-- already exists the batch must abort so you can look at why, rather than skip
-- it and leave the schema half-migrated.
-- ============================================================================



-- ============================================================================
-- FILE: 0031_delegated_authorities_tenant.sql
-- ============================================================================

-- 0031_delegated_authorities_tenant.sql
-- authorization-svc → schema `authorization_svc`. Creates no tables.
--
-- The change authorization-svc's own 000006_add_delegation_tenant makes, in the
-- form this project applies it. Same statements, same end state; whichever runs
-- first, the other is a no-op.
--
-- ── What this closes ─────────────────────────────────────────────────────────
--
-- 0028 gave permission_bundles and principal_role_assignments row security
-- through their parent role, and left one table alone, saying so explicitly:
--
--   "delegated_authorities still has no row security. It carries neither
--    tenant_id nor role_id, so there is no path to a tenant to write a policy
--    against, and giving it one means a column the service INSERT does not
--    supply — a change to authorization-svc, not to its schema."
--
-- That is exactly right, and it is why this migration ships alongside the
-- service change rather than on its own. authorization-svc now resolves the
-- caller's verified tenant on both delegation routes and supplies it on INSERT;
-- without that, the NOT NULL below would reject every write.
--
-- With this applied, delegated_authorities is the last table in this schema to
-- gain row security — `verify.sh`'s "tables with NO row-level security at all"
-- check then covers authorization_svc completely.
--
-- ── What was exposed ─────────────────────────────────────────────────────────
--
-- A delegation says "principal X may act with principal Y's authority". Every
-- read and write of it ran with no tenant predicate and no policy:
--
--   FindDelegatedAuthorityByID   WHERE delegated_authority_id = $1 only
--   RevokeDelegatedAuthority     WHERE delegated_authority_id = $1 only
--   FindDelegatedActions         WHERE delegate_principal_id = $1 only
--
-- The handler's ownership check (only the delegator may revoke) bounded the
-- damage. Nothing bounded it by tenant.
--
-- ── Guarded, like 0027 and 0028 ──────────────────────────────────────────────
--
-- `authorization_svc` is not created by anything in this directory — it arrives
-- via deployments/supabase applying the service's own migrations. On a fresh
-- project, and in supabase/verify.sh, the schema is genuinely absent, and bare
-- DDL would abort the whole batch and silently skip everything numbered after.

DO $guard$
DECLARE untenanted int;
BEGIN

IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'authorization_svc') THEN
    RAISE NOTICE 'schema authorization_svc absent; skipping 0031 — re-run it after deployments/supabase has created the schema';
    RETURN;
END IF;

EXECUTE $stmt$ALTER TABLE authorization_svc.delegated_authorities ADD COLUMN IF NOT EXISTS tenant_id UUID$stmt$;

-- NOT NULL because a NULL tenant here is not "global" — it is a row no policy
-- can ever match, so the delegation exists and silently never grants anything.
-- The table held 0 rows when this was surveyed; if that has changed, stop
-- rather than invent a tenant for a row describing who may act for whom.
SELECT count(*) INTO untenanted
  FROM authorization_svc.delegated_authorities
 WHERE tenant_id IS NULL;
IF untenanted > 0 THEN
    RAISE EXCEPTION
        '% delegated_authorities rows have no tenant_id. Backfill them from the delegator''s tenant before re-running: a NULL tenant matches no policy, so those delegations would exist and never grant anything.',
        untenanted;
END IF;

EXECUTE $stmt$ALTER TABLE authorization_svc.delegated_authorities ALTER COLUMN tenant_id SET NOT NULL$stmt$;

-- The evaluation lookup FindDelegatedActions performs, now tenant-first.
EXECUTE $stmt$
CREATE INDEX IF NOT EXISTS idx_delegations_tenant_lookup
    ON authorization_svc.delegated_authorities (tenant_id, delegate_principal_id, revocation_status)
$stmt$;

EXECUTE $stmt$ALTER TABLE authorization_svc.delegated_authorities ENABLE ROW LEVEL SECURITY$stmt$;
EXECUTE $stmt$ALTER TABLE authorization_svc.delegated_authorities FORCE  ROW LEVEL SECURITY$stmt$;

-- app.current_tenant_id() rather than current_setting directly: on this
-- database a caller may arrive through PostgREST with a JWT instead of through
-- a service calling set_config, and only the helper resolves both. The service
-- migration uses current_setting because the app schema does not exist on the
-- compose estate.
--
-- No platform_scope hatch, unlike roles: nothing needs to discover which tenant
-- owns an unknown delegation_id.
EXECUTE $stmt$DROP POLICY IF EXISTS tenant_isolation_policy ON authorization_svc.delegated_authorities$stmt$;
EXECUTE $stmt$
CREATE POLICY tenant_isolation_policy ON authorization_svc.delegated_authorities
    FOR ALL
    USING      (tenant_id::text = app.current_tenant_id())
    WITH CHECK (tenant_id::text = app.current_tenant_id())
$stmt$;

-- ── Verification ─────────────────────────────────────────────────────────────

DECLARE unprotected int; no_check int;
BEGIN
    SELECT count(*) INTO unprotected
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'authorization_svc' AND c.relkind = 'r'
       AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
    IF unprotected > 0 THEN
        RAISE EXCEPTION
            '% authorization_svc tables still lack forced row security — delegated_authorities was meant to be the last one', unprotected;
    END IF;

    SELECT count(*) INTO no_check
      FROM pg_policies
     WHERE schemaname = 'authorization_svc'
       AND tablename = 'delegated_authorities'
       AND with_check IS NULL;
    IF no_check > 0 THEN
        RAISE EXCEPTION 'delegated_authorities policy has no WITH CHECK';
    END IF;

    RAISE NOTICE 'verified: authorization_svc now has forced row security on every table';
END;

END
$guard$;
