-- ============================================================================
-- Zoiko Suite — Supabase migrations 0022 to 0026.
--
-- Generated by supabase/build-delta.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- A DELTA, for a project that already has the earlier migrations applied.
-- For a fresh project use zoiko-suite-all.sql instead — this file assumes
-- 0001_platform_foundation has already created:
--
--   - the zoiko_backend role
--   - the app schema, app.current_tenant_id() and app.current_principal_id()
--
-- Verify what is already applied before pasting this:
--
--   SELECT nspname FROM pg_namespace
--    WHERE nspname NOT LIKE 'pg_%'
--      AND nspname NOT IN ('information_schema','public')
--    ORDER BY 1;
--
-- Every CREATE below is bare, not IF NOT EXISTS, on purpose: if something here
-- already exists the batch must abort so you can look at why, rather than skip
-- it and leave the schema half-migrated.
-- ============================================================================



-- ============================================================================
-- FILE: 0022_employee_master_svc.sql
-- ============================================================================

-- 0022_employee_master_svc.sql
-- employee-master-svc → schema `employee_master`
--
-- Squashed end state of 000001_initial_schema and 000002_hr_profile_fields.
-- One table: employees.
--
-- ── This service is the employee identity other services resolve against ─────
-- leave-absence-svc, compensation-svc and payroll-run-svc all call
-- GET /v1/employees/{id} to learn which legal entity an employee belongs to,
-- and each fails closed when it cannot. That makes this table the root of the
-- HR domain's scope resolution, which is why it lands before the three
-- migrations that follow it.
--
-- ── Personal data is separated from employment data ──────────────────────────
-- The Go store reads two different projections: a full one for a single
-- employee, and a directory one for a listing that deliberately omits date of
-- birth, gender, personal email and both address fields. A caller enumerating a
-- legal entity is building a directory or a headcount rollup and needs none of
-- them.
--
-- That split is a projection in the service, not a boundary in the schema, so
-- it protects nothing here on its own. The `employee_directory` view below
-- makes it real for anything reaching the table through PostgREST: the
-- `authenticated` role is granted the view and nothing on the base table.
--
-- ── Gender is optional to disclose ───────────────────────────────────────────
-- NULL and 'UNSPECIFIED' mean different things and both are allowed. NULL is
-- "never asked"; UNSPECIFIED is a choice the employee made. Collapsing them
-- would discard the distinction and misreport the second as missing data.

CREATE SCHEMA IF NOT EXISTS employee_master;

COMMENT ON SCHEMA employee_master IS
    'employee-master-svc. Authoritative employee record and the legal-entity scope other HR services resolve against. Holds personal data — expose employee_directory through PostgREST, not the base table.';

GRANT USAGE ON SCHEMA employee_master TO zoiko_backend, authenticated;

-- ── employees ────────────────────────────────────────────────────────────────

CREATE TABLE employee_master.employees (
    employee_id         UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           VARCHAR(255) NOT NULL,
    legal_entity_id     VARCHAR(255) NOT NULL,

    employee_number     VARCHAR(100) NOT NULL,
    first_name          VARCHAR(100) NOT NULL,
    last_name           VARCHAR(100) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    phone               VARCHAR(50),
    job_title           VARCHAR(150) NOT NULL DEFAULT 'Employee',

    department_id       VARCHAR(255),
    manager_employee_id UUID,

    -- FULL_TIME | PART_TIME | CONTRACTOR
    worker_type         VARCHAR(50)  NOT NULL,
    -- ONBOARDING | ACTIVE | SUSPENDED | TERMINATED
    status              VARCHAR(50)  NOT NULL,

    hire_date           DATE         NOT NULL,
    termination_date    DATE,

    effective_from      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    effective_to        TIMESTAMPTZ,

    -- ── Personal profile ────────────────────────────────────────────────────
    date_of_birth       DATE,
    gender              VARCHAR(30),
    profile_picture_url VARCHAR(500),
    personal_email      VARCHAR(255),
    work_email          VARCHAR(255),

    -- ── Address ─────────────────────────────────────────────────────────────
    current_address     TEXT,
    permanent_address   TEXT,
    city                VARCHAR(100),
    state               VARCHAR(100),
    country             VARCHAR(100),
    postal_code         VARCHAR(20),

    -- ── Org placement ───────────────────────────────────────────────────────
    -- Reporting labels alongside the authoritative department_id.
    -- org-structure-svc owns the real hierarchy; these are the free-text
    -- groupings HR reporting and payroll cost splits need.
    company             VARCHAR(200),
    business_unit       VARCHAR(200),
    division            VARCHAR(200),
    team                VARCHAR(200),
    designation_id      VARCHAR(255),
    confirmation_date   DATE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- The vocabulary the domain defines, enforced in Go and — before this —
    -- nowhere else, so any other writer could leave a value no consumer knows
    -- how to read.
    CONSTRAINT employees_worker_type_known
        CHECK (worker_type IN ('FULL_TIME', 'PART_TIME', 'CONTRACTOR')),
    CONSTRAINT employees_status_known
        CHECK (status IN ('ONBOARDING', 'ACTIVE', 'SUSPENDED', 'TERMINATED')),

    -- Optional to disclose, so nullable; a controlled vocabulary when given.
    CONSTRAINT employees_gender_check
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE', 'NON_BINARY', 'OTHER', 'UNSPECIFIED')),

    -- Nobody was confirmed before they were hired.
    CONSTRAINT employees_confirmation_after_hire_check
        CHECK (confirmation_date IS NULL OR confirmation_date >= hire_date),

    -- Nor terminated before they were hired.
    CONSTRAINT employees_termination_after_hire_check
        CHECK (termination_date IS NULL OR termination_date >= hire_date),

    -- A TERMINATED employee must say when. Without this, a terminated row is a
    -- record that somebody left and no account of when — which is the whole
    -- reason downstream payroll reads the status at all.
    CONSTRAINT employees_terminated_has_date
        CHECK (status <> 'TERMINATED' OR termination_date IS NOT NULL),

    -- An employee is not their own manager. A self-reference would make the
    -- reporting chain a cycle of one and hang any recursive walk of it.
    CONSTRAINT employees_manager_not_self
        CHECK (manager_employee_id IS NULL OR manager_employee_id <> employee_id),

    -- The target of the composite self-reference below.
    CONSTRAINT employees_tenant_id_unique UNIQUE (tenant_id, employee_id)
);

-- A manager in another tenant is unrepresentable. The single-column form would
-- have accepted one: nothing made the referenced row's tenant agree with this
-- one's, and a reporting chain that crosses tenants leaks the org structure of
-- both.
ALTER TABLE employee_master.employees
    ADD CONSTRAINT employees_manager_same_tenant
    FOREIGN KEY (tenant_id, manager_employee_id)
    REFERENCES employee_master.employees (tenant_id, employee_id);

CREATE UNIQUE INDEX idx_employees_tenant_email
    ON employee_master.employees (tenant_id, email);
CREATE UNIQUE INDEX idx_employees_tenant_number
    ON employee_master.employees (tenant_id, employee_number);

-- Work email is an addressable identity inside a tenant, so it carries the same
-- uniqueness guarantee as the primary email. Partial: the many rows with no
-- work email must not collide with each other.
CREATE UNIQUE INDEX idx_employees_tenant_work_email
    ON employee_master.employees (tenant_id, work_email)
    WHERE work_email IS NOT NULL;

CREATE INDEX idx_employees_tenant_entity_status
    ON employee_master.employees (tenant_id, legal_entity_id, status);
CREATE INDEX idx_employees_tenant_dept
    ON employee_master.employees (tenant_id, department_id);
CREATE INDEX idx_employees_tenant_manager
    ON employee_master.employees (tenant_id, manager_employee_id);

-- Reporting rollups filter on these; without them a division-level headcount
-- query degrades to a full scan of the tenant's employees.
CREATE INDEX idx_employees_tenant_business_unit
    ON employee_master.employees (tenant_id, business_unit)
    WHERE business_unit IS NOT NULL;
CREATE INDEX idx_employees_tenant_division
    ON employee_master.employees (tenant_id, division)
    WHERE division IS NOT NULL;
CREATE INDEX idx_employees_tenant_designation
    ON employee_master.employees (tenant_id, designation_id)
    WHERE designation_id IS NOT NULL;

-- ── Row-level security ───────────────────────────────────────────────────────

ALTER TABLE employee_master.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_master.employees FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON employee_master.employees
    FOR ALL
    TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

-- ── employee_directory ───────────────────────────────────────────────────────
--
-- The directory projection, as a view rather than a convention. This is the
-- only employee data `authenticated` can reach: date of birth, gender, personal
-- email and both addresses are absent, and no grant on the base table restores
-- them.
--
-- security_invoker so the view runs under the caller's own privileges and the
-- table's RLS still applies. Without it the view would run as its owner and
-- hand every tenant's directory to every caller.

CREATE VIEW employee_master.employee_directory
WITH (security_invoker = true) AS
SELECT
    employee_id,
    tenant_id,
    legal_entity_id,
    employee_number,
    first_name,
    last_name,
    email,
    work_email,
    phone,
    job_title,
    department_id,
    manager_employee_id,
    worker_type,
    status,
    hire_date,
    termination_date,
    company,
    business_unit,
    division,
    team,
    designation_id,
    confirmation_date,
    created_at,
    updated_at
FROM employee_master.employees;

COMMENT ON VIEW employee_master.employee_directory IS
    'Employment data without personal data. Omits date_of_birth, gender, profile_picture_url, personal_email and both address fields. This is what authenticated callers read; the base table is reachable only by zoiko_backend.';

-- ── Grants ───────────────────────────────────────────────────────────────────

-- No DELETE: an employee record is the basis of every payslip, leave balance
-- and contract that referenced it. Departure is a status change, and
-- effective_to closes the row.
GRANT SELECT, INSERT, UPDATE ON employee_master.employees TO zoiko_backend;

-- Nothing on the base table for authenticated — only the directory view.
GRANT SELECT ON employee_master.employee_directory TO authenticated;


-- ============================================================================
-- FILE: 0023_leave_absence_svc.sql
-- ============================================================================

-- 0023_leave_absence_svc.sql
-- leave-absence-svc → schema `leave_absence`
--
-- Squashed end state of 000001_initial_schema, 000002_fix_race_and_idempotency
-- and 000003_leave_policy_and_holidays. Four tables: leave_types,
-- leave_balances, leave_requests, holidays.
--
-- Depends on 0022: an employee_id here is an employee_master employee, and the
-- service resolves the employee's legal entity through that service before it
-- authorizes anything.
--
-- ── Leave policy is enforced, not advisory ───────────────────────────────────
-- Before 000003 a leave type carried an accrual rate and a cap and nothing
-- else, so every request was reviewed by hand and nothing stopped someone
-- booking six months starting tomorrow. min_notice_days, max_consecutive_days
-- and requires_approval are checked by the service at submission time.
--
-- requires_approval DEFAULTs true. A leave type that arrives without the column
-- set must not silently stop being reviewed.
--
-- ── Holidays are retired, never deleted ──────────────────────────────────────
-- Leave approved against last year's calendar has to stay explicable, so a
-- holiday moves to INACTIVE and the row stays. The uniqueness index is partial
-- on ACTIVE so a retired date can be declared again.

CREATE SCHEMA IF NOT EXISTS leave_absence;

COMMENT ON SCHEMA leave_absence IS
    'leave-absence-svc. Leave types and their policy, per-employee balances, requests, and the holiday calendar. Policy on a leave type is enforced at submission, not advisory.';

GRANT USAGE ON SCHEMA leave_absence TO zoiko_backend, authenticated;

-- ── leave_types ──────────────────────────────────────────────────────────────

CREATE TABLE leave_absence.leave_types (
    leave_type_id           UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id               VARCHAR(255) NOT NULL,
    legal_entity_id         VARCHAR(255) NOT NULL,

    name                    VARCHAR(255) NOT NULL,
    -- VACATION | SICK_LEAVE | MATERNITY | PATERNITY | BEREAVEMENT | UNPAID | ...
    -- Deliberately not a CHECK: a legal entity may define its own statutory
    -- leave types, and the set is jurisdiction-dependent.
    code                    VARCHAR(50)  NOT NULL,

    is_paid                 BOOLEAN      NOT NULL DEFAULT true,
    accrual_rate_per_year   NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    max_balance             NUMERIC(10, 2) NOT NULL DEFAULT 0.00,

    -- ACTIVE | INACTIVE
    status                  VARCHAR(50)  NOT NULL,

    -- ── Policy ──────────────────────────────────────────────────────────────
    carry_forward_allowed   BOOLEAN      NOT NULL DEFAULT false,
    carry_forward_max_hours NUMERIC(10, 2) NOT NULL DEFAULT 0.00,

    -- Minimum days between submitting and the leave starting. 0 permits
    -- same-day and retroactive booking, which is what sick leave needs.
    min_notice_days         INTEGER      NOT NULL DEFAULT 0,

    -- Longest unbroken span, in calendar days, one request may cover.
    -- 0 means unlimited.
    max_consecutive_days    INTEGER      NOT NULL DEFAULT 0,

    -- false auto-approves on submission.
    requires_approval       BOOLEAN      NOT NULL DEFAULT true,

    -- Display metadata carried for the caller. The service never reads these.
    color_hex               VARCHAR(7),
    icon                    VARCHAR(50),

    created_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT leave_types_status_known
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT leave_types_notice_non_negative_check
        CHECK (min_notice_days >= 0
           AND max_consecutive_days >= 0
           AND carry_forward_max_hours >= 0
           AND accrual_rate_per_year >= 0
           AND max_balance >= 0),

    -- Carrying forward with a zero cap would silently discard the whole balance
    -- at year end, which reads as a policy bug rather than a policy.
    CONSTRAINT leave_types_carry_forward_cap_check
        CHECK (NOT carry_forward_allowed OR carry_forward_max_hours > 0),

    CONSTRAINT leave_types_tenant_id_unique UNIQUE (tenant_id, leave_type_id)
);

-- A leave type code is the stable handle policy is configured against, so it
-- must not repeat within a legal entity.
CREATE UNIQUE INDEX idx_leave_types_tenant_entity_code
    ON leave_absence.leave_types (tenant_id, legal_entity_id, code);

CREATE INDEX idx_leave_types_tenant_entity
    ON leave_absence.leave_types (tenant_id, legal_entity_id);

-- ── leave_balances ───────────────────────────────────────────────────────────

CREATE TABLE leave_absence.leave_balances (
    balance_id      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       VARCHAR(255) NOT NULL,
    employee_id     UUID         NOT NULL,
    leave_type_id   UUID         NOT NULL,

    allocated_hours NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    used_hours      NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    pending_hours   NUMERIC(10, 2) NOT NULL DEFAULT 0.00,

    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- A balance in one tenant against another tenant's leave type is
    -- unrepresentable. The single-column reference in 000001 accepted it.
    CONSTRAINT leave_balances_type_same_tenant
        FOREIGN KEY (tenant_id, leave_type_id)
        REFERENCES leave_absence.leave_types (tenant_id, leave_type_id),

    CONSTRAINT unique_tenant_emp_leave_type
        UNIQUE (tenant_id, employee_id, leave_type_id),

    -- Hours are quantities, never negative. Used and pending hours that exceed
    -- what was allocated would report an available balance below zero, which
    -- the service treats as insufficient and would then never let anyone spend.
    CONSTRAINT leave_balances_hours_non_negative
        CHECK (allocated_hours >= 0 AND used_hours >= 0 AND pending_hours >= 0)
);

CREATE INDEX idx_leave_balances_tenant_emp
    ON leave_absence.leave_balances (tenant_id, employee_id);

-- ── leave_requests ───────────────────────────────────────────────────────────

CREATE TABLE leave_absence.leave_requests (
    request_id     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      VARCHAR(255) NOT NULL,
    employee_id    UUID         NOT NULL,
    leave_type_id  UUID         NOT NULL,

    start_date     DATE         NOT NULL,
    end_date       DATE         NOT NULL,
    total_hours    NUMERIC(10, 2) NOT NULL,
    reason         TEXT,

    -- SUBMITTED | APPROVED | REJECTED | CANCELLED
    status         VARCHAR(50)  NOT NULL,

    reviewer_id    VARCHAR(255),
    reviewer_notes TEXT,
    reviewed_at    TIMESTAMPTZ,

    correlation_id VARCHAR(255) NOT NULL DEFAULT '',

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT leave_requests_type_same_tenant
        FOREIGN KEY (tenant_id, leave_type_id)
        REFERENCES leave_absence.leave_types (tenant_id, leave_type_id),

    CONSTRAINT leave_requests_status_known
        CHECK (status IN ('SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED')),

    -- Leave that ends before it starts is not a span. The service checks this;
    -- nothing else did.
    CONSTRAINT leave_requests_end_after_start
        CHECK (end_date >= start_date),

    CONSTRAINT leave_requests_hours_positive
        CHECK (total_hours > 0),

    -- A reviewed request must record who reviewed it and when. A row reading
    -- APPROVED with no reviewer is an approval nobody is accountable for.
    CONSTRAINT leave_requests_reviewed_has_reviewer
        CHECK (
            status IN ('SUBMITTED', 'CANCELLED')
            OR (reviewer_id IS NOT NULL AND reviewed_at IS NOT NULL)
        )
);

-- Idempotency: a retried submit resolves to the original request instead of
-- creating a duplicate and double-locking pending hours.
CREATE UNIQUE INDEX idx_leave_requests_tenant_correlation
    ON leave_absence.leave_requests (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_leave_requests_tenant_emp
    ON leave_absence.leave_requests (tenant_id, employee_id);
CREATE INDEX idx_leave_requests_tenant_status
    ON leave_absence.leave_requests (tenant_id, status);

-- ── holidays ─────────────────────────────────────────────────────────────────
--
-- Public and company holidays per legal entity. Leave spanning a holiday should
-- not consume balance for that day, and before 000003 there was nowhere to
-- record which days those are.

CREATE TABLE leave_absence.holidays (
    holiday_id      UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       VARCHAR(255) NOT NULL,
    legal_entity_id VARCHAR(255) NOT NULL,

    name            VARCHAR(150) NOT NULL,
    holiday_date    DATE         NOT NULL,

    -- PUBLIC | COMPANY | OPTIONAL
    holiday_type    VARCHAR(50)  NOT NULL DEFAULT 'PUBLIC',

    -- Same calendar day every year.
    is_recurring    BOOLEAN      NOT NULL DEFAULT false,
    description     TEXT,

    -- ACTIVE | INACTIVE
    status          VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT holidays_type_check
        CHECK (holiday_type IN ('PUBLIC', 'COMPANY', 'OPTIONAL')),
    CONSTRAINT holidays_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- One entry per day per entity. Partial on ACTIVE so a day can be retired and
-- then re-declared without tripping over the old row.
CREATE UNIQUE INDEX idx_holidays_tenant_entity_date
    ON leave_absence.holidays (tenant_id, legal_entity_id, holiday_date)
    WHERE status = 'ACTIVE';

-- The calendar is read by date range far more often than by anything else.
CREATE INDEX idx_holidays_tenant_entity_range
    ON leave_absence.holidays (tenant_id, legal_entity_id, holiday_date, status);

-- ── Row-level security ───────────────────────────────────────────────────────

ALTER TABLE leave_absence.leave_types    ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_absence.leave_types    FORCE  ROW LEVEL SECURITY;
ALTER TABLE leave_absence.leave_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_absence.leave_balances FORCE  ROW LEVEL SECURITY;
ALTER TABLE leave_absence.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_absence.leave_requests FORCE  ROW LEVEL SECURITY;
ALTER TABLE leave_absence.holidays       ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_absence.holidays       FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON leave_absence.leave_types
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON leave_absence.leave_balances
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON leave_absence.leave_requests
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON leave_absence.holidays
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

-- Leave types and the holiday calendar are policy an employee is entitled to
-- read: they say how much notice a request needs and which days are not working
-- days. Balances and requests are not — those are one employee's own record.
CREATE POLICY tenant_read ON leave_absence.leave_types
    FOR SELECT TO authenticated
    USING (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_read ON leave_absence.holidays
    FOR SELECT TO authenticated
    USING (tenant_id = app.current_tenant_id() AND status = 'ACTIVE');

-- ── Grants ───────────────────────────────────────────────────────────────────

-- No DELETE anywhere: a leave request is the record of an absence that was
-- taken or refused, a balance is the running account behind it, and a holiday
-- explains a payslip. All three retire by status or end-date instead.
GRANT SELECT, INSERT, UPDATE ON leave_absence.leave_types    TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON leave_absence.leave_balances TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON leave_absence.leave_requests TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON leave_absence.holidays       TO zoiko_backend;

GRANT SELECT ON leave_absence.leave_types TO authenticated;
GRANT SELECT ON leave_absence.holidays    TO authenticated;


-- ============================================================================
-- FILE: 0024_compensation_svc.sql
-- ============================================================================

-- 0024_compensation_svc.sql
-- compensation-svc → schema `compensation`
--
-- Squashed end state of 000001_initial_schema, 000002_fix_race_and_idempotency
-- and 000003_salary_components. Five tables: compensation_structures,
-- wage_revisions, bonus_grants, salary_components, structure_components.
--
-- Depends on 0022: an employee_id here is an employee_master employee.
--
-- ── What 000003 added, and why ───────────────────────────────────────────────
-- A compensation_structure was a min/max band and nothing else, so nothing
-- downstream could answer "what is this salary actually made of". Payroll needs
-- the breakdown: which elements are earnings, which are deductions, which are
-- taxable, and how each is derived from the base. payroll-run-svc reads it
-- through /v1/compensation/structures/{id}/breakdown and puts the resulting
-- lines on the payslip.
--
-- ── Derivations are modelled, not evaluated ──────────────────────────────────
-- zoiko-one, where this was ported from, stored the amount as a free-text
-- `amount_or_formula VARCHAR(255)`. That does not travel: a governance service
-- cannot evaluate arbitrary expressions and still explain a payslip. The two
-- derivations payroll actually needs are declared explicitly instead — a fixed
-- amount, or a percentage of the base.
--
-- Percentages resolve against the base, never against a running total, so the
-- result does not depend on the order the components happen to be stored in.
-- That property lives in the service; the schema keeps the inputs honest.

CREATE SCHEMA IF NOT EXISTS compensation;

COMMENT ON SCHEMA compensation IS
    'compensation-svc. Pay structures and what they are composed of, wage revision history, and bonus grants. The component breakdown is what payroll-run-svc resolves a payslip from.';

GRANT USAGE ON SCHEMA compensation TO zoiko_backend, authenticated;

-- ── compensation_structures ──────────────────────────────────────────────────

CREATE TABLE compensation.compensation_structures (
    structure_id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           VARCHAR(255) NOT NULL,
    legal_entity_id     VARCHAR(255) NOT NULL,

    name                VARCHAR(150) NOT NULL,
    -- SALARY | HOURLY
    pay_type            VARCHAR(50)  NOT NULL,

    min_amount          NUMERIC(18, 4) NOT NULL,
    max_amount          NUMERIC(18, 4) NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    overtime_multiplier NUMERIC(5, 2) NOT NULL DEFAULT 1.50,

    correlation_id      VARCHAR(255) NOT NULL DEFAULT '',

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT comp_structures_pay_type_known
        CHECK (pay_type IN ('SALARY', 'HOURLY')),

    -- An inverted band admits no salary at all, and every later "is this wage
    -- inside its band" check would answer no for every possible amount.
    CONSTRAINT comp_structures_band_ordered
        CHECK (max_amount >= min_amount),
    CONSTRAINT comp_structures_amounts_non_negative
        CHECK (min_amount >= 0),

    -- Overtime paid below the normal rate is not overtime.
    CONSTRAINT comp_structures_overtime_at_least_one
        CHECK (overtime_multiplier >= 1.00),

    CONSTRAINT comp_structures_tenant_id_unique UNIQUE (tenant_id, structure_id)
);

CREATE UNIQUE INDEX idx_comp_struct_tenant_correlation
    ON compensation.compensation_structures (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_comp_struct_tenant_entity
    ON compensation.compensation_structures (tenant_id, legal_entity_id);

-- ── wage_revisions ───────────────────────────────────────────────────────────

CREATE TABLE compensation.wage_revisions (
    revision_id    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      VARCHAR(255) NOT NULL,
    employee_id    UUID         NOT NULL,
    structure_id   UUID,

    -- SALARY | HOURLY
    pay_type       VARCHAR(50)  NOT NULL,
    amount         NUMERIC(18, 4) NOT NULL,
    currency       VARCHAR(3)   NOT NULL,

    effective_from DATE         NOT NULL,
    effective_to   DATE,

    reason         TEXT         NOT NULL,
    revised_by     VARCHAR(255) NOT NULL DEFAULT app.current_principal_id(),

    -- ACTIVE | SUPERSEDED
    status         VARCHAR(50)  NOT NULL,

    correlation_id VARCHAR(255) NOT NULL DEFAULT '',

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- A revision against another tenant's structure is unrepresentable.
    CONSTRAINT wage_revisions_structure_same_tenant
        FOREIGN KEY (tenant_id, structure_id)
        REFERENCES compensation.compensation_structures (tenant_id, structure_id),

    CONSTRAINT wage_revisions_pay_type_known
        CHECK (pay_type IN ('SALARY', 'HOURLY')),
    CONSTRAINT wage_revisions_status_known
        CHECK (status IN ('ACTIVE', 'SUPERSEDED')),
    CONSTRAINT wage_revisions_amount_non_negative
        CHECK (amount >= 0),

    -- A revision that ends before it starts was never in force.
    CONSTRAINT wage_revisions_period_ordered
        CHECK (effective_to IS NULL OR effective_to >= effective_from),

    -- The ACTIVE revision is the one in force now, so it has no end date.
    -- Without this, a row could read ACTIVE with an effective_to in the past
    -- and payroll would keep paying it.
    CONSTRAINT wage_revisions_active_is_open
        CHECK (status <> 'ACTIVE' OR effective_to IS NULL)
);

-- At most one ACTIVE wage revision per employee, at the database level. Without
-- it, two concurrent ReviseWage calls could both pass the application's
-- supersede-then-insert sequence and leave two ACTIVE rows — and
-- GetActiveWageRevision (LIMIT 1, no ORDER BY) would hand payroll an arbitrary
-- one of them.
CREATE UNIQUE INDEX idx_wage_revisions_one_active
    ON compensation.wage_revisions (tenant_id, employee_id)
    WHERE status = 'ACTIVE';

CREATE UNIQUE INDEX idx_wage_rev_tenant_correlation
    ON compensation.wage_revisions (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_wage_rev_tenant_emp
    ON compensation.wage_revisions (tenant_id, employee_id);
CREATE INDEX idx_wage_rev_tenant_status
    ON compensation.wage_revisions (tenant_id, status);

-- ── bonus_grants ─────────────────────────────────────────────────────────────

CREATE TABLE compensation.bonus_grants (
    grant_id       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id      VARCHAR(255) NOT NULL,
    employee_id    UUID         NOT NULL,

    -- PERFORMANCE | ANNUAL | SIGNING | RETENTION
    bonus_type     VARCHAR(50)  NOT NULL,
    amount         NUMERIC(18, 4) NOT NULL,
    currency       VARCHAR(3)   NOT NULL,
    grant_date     DATE         NOT NULL,

    -- PENDING | APPROVED | PAID | CANCELLED
    status         VARCHAR(50)  NOT NULL,
    approved_by    VARCHAR(255),

    correlation_id VARCHAR(255) NOT NULL DEFAULT '',

    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT bonus_grants_type_known
        CHECK (bonus_type IN ('PERFORMANCE', 'ANNUAL', 'SIGNING', 'RETENTION')),
    CONSTRAINT bonus_grants_status_known
        CHECK (status IN ('PENDING', 'APPROVED', 'PAID', 'CANCELLED')),
    CONSTRAINT bonus_grants_amount_non_negative
        CHECK (amount >= 0),

    -- An approved or paid bonus names who approved it. Money that moved with
    -- nobody accountable for the decision is the thing this table exists to
    -- prevent.
    CONSTRAINT bonus_grants_approved_has_approver
        CHECK (status NOT IN ('APPROVED', 'PAID') OR approved_by IS NOT NULL)
);

CREATE UNIQUE INDEX idx_bonus_grants_tenant_correlation
    ON compensation.bonus_grants (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_bonus_grants_tenant_emp
    ON compensation.bonus_grants (tenant_id, employee_id);
CREATE INDEX idx_bonus_grants_tenant_status
    ON compensation.bonus_grants (tenant_id, status);

-- ── salary_components ────────────────────────────────────────────────────────
--
-- The catalogue of pay elements a legal entity can compose into its structures.

CREATE TABLE compensation.salary_components (
    component_id    UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id       VARCHAR(255) NOT NULL,
    legal_entity_id VARCHAR(255) NOT NULL,

    name            VARCHAR(150) NOT NULL,
    -- HRA, TRANSPORT, PF, PROF_TAX, ... Entity-defined, so no CHECK.
    code            VARCHAR(50)  NOT NULL,

    -- EARNING | DEDUCTION
    component_type  VARCHAR(20)  NOT NULL,

    -- Taxable unless stated otherwise. Defaulting the other way would
    -- under-report income by omission.
    is_taxable      BOOLEAN      NOT NULL DEFAULT true,

    default_amount  NUMERIC(18, 4),
    currency        VARCHAR(3)   NOT NULL,
    description     TEXT,

    -- ACTIVE | INACTIVE
    status          VARCHAR(50)  NOT NULL DEFAULT 'ACTIVE',

    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT salary_components_type_check
        CHECK (component_type IN ('EARNING', 'DEDUCTION')),
    CONSTRAINT salary_components_status_check
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    -- A negative component would flip an earning into a deduction by stealth.
    CONSTRAINT salary_components_amount_check
        CHECK (default_amount IS NULL OR default_amount >= 0),

    CONSTRAINT salary_components_tenant_id_unique UNIQUE (tenant_id, component_id)
);

-- A component code is the stable handle payroll refers to, so it is unique
-- within a legal entity. Partial on ACTIVE so a retired code can be reissued.
CREATE UNIQUE INDEX idx_salary_components_entity_code
    ON compensation.salary_components (tenant_id, legal_entity_id, code)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_salary_components_tenant_entity
    ON compensation.salary_components (tenant_id, legal_entity_id, status);

-- ── structure_components ─────────────────────────────────────────────────────
--
-- Which components make up a structure, and how each is derived.

CREATE TABLE compensation.structure_components (
    structure_component_id UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id              VARCHAR(255) NOT NULL,
    structure_id           UUID         NOT NULL,
    component_id           UUID         NOT NULL,

    -- FIXED | PERCENT_OF_BASE
    calculation_method     VARCHAR(30)  NOT NULL,
    calculation_value      NUMERIC(18, 4) NOT NULL,

    -- Payslip display order.
    sequence               INTEGER      NOT NULL DEFAULT 0,

    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- Both parents must be in this row's tenant. A structure composed from
    -- another entity's components would produce a payslip that crosses a legal
    -- boundary, and the single-column form would have allowed it.
    CONSTRAINT structure_components_structure_same_tenant
        FOREIGN KEY (tenant_id, structure_id)
        REFERENCES compensation.compensation_structures (tenant_id, structure_id),
    CONSTRAINT structure_components_component_same_tenant
        FOREIGN KEY (tenant_id, component_id)
        REFERENCES compensation.salary_components (tenant_id, component_id),

    CONSTRAINT structure_components_method_check
        CHECK (calculation_method IN ('FIXED', 'PERCENT_OF_BASE')),
    CONSTRAINT structure_components_value_check
        CHECK (calculation_value >= 0),

    -- A percentage over 100 of the base is a data-entry slip, not a policy.
    CONSTRAINT structure_components_percent_range_check
        CHECK (calculation_method <> 'PERCENT_OF_BASE' OR calculation_value <= 100),

    -- One line per component per structure; changing the amount updates the row.
    CONSTRAINT structure_components_unique UNIQUE (structure_id, component_id)
);

-- Reading a structure's composition is the hot path: payroll does it per
-- employee per run, always in payslip order.
CREATE INDEX idx_structure_components_structure
    ON compensation.structure_components (tenant_id, structure_id, sequence);

-- ── Row-level security ───────────────────────────────────────────────────────

ALTER TABLE compensation.compensation_structures ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation.compensation_structures FORCE  ROW LEVEL SECURITY;
ALTER TABLE compensation.wage_revisions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation.wage_revisions          FORCE  ROW LEVEL SECURITY;
ALTER TABLE compensation.bonus_grants            ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation.bonus_grants            FORCE  ROW LEVEL SECURITY;
ALTER TABLE compensation.salary_components       ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation.salary_components       FORCE  ROW LEVEL SECURITY;
ALTER TABLE compensation.structure_components    ENABLE ROW LEVEL SECURITY;
ALTER TABLE compensation.structure_components    FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON compensation.compensation_structures
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON compensation.wage_revisions
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON compensation.bonus_grants
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON compensation.salary_components
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON compensation.structure_components
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

-- Nothing here is readable by `authenticated`. Every table in this schema is
-- either an individual's pay or the bands and components that would let one
-- employee derive a colleague's. Reads go through the service, which resolves
-- the caller's own employee_id first.

-- ── Grants ───────────────────────────────────────────────────────────────────

-- wage_revisions and bonus_grants take no DELETE and no UPDATE beyond the
-- supersede/approve transitions the service performs: both are the history of
-- what somebody was paid and who decided it.
GRANT SELECT, INSERT, UPDATE ON compensation.compensation_structures TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON compensation.wage_revisions          TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON compensation.bonus_grants            TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE ON compensation.salary_components       TO zoiko_backend;

-- structure_components is the exception that needs DELETE: a structure's
-- composition is replaced as a set, and a partial write would leave a structure
-- computing a payslip nobody intended. The service clears and re-inserts inside
-- one transaction.
GRANT SELECT, INSERT, UPDATE, DELETE ON compensation.structure_components TO zoiko_backend;


-- ============================================================================
-- FILE: 0025_payroll_run_svc.sql
-- ============================================================================

-- 0025_payroll_run_svc.sql
-- payroll-run-svc → schema `payroll_run`
--
-- Squashed end state of 000001_initial_schema, 000002_add_idempotency_index,
-- 000003_add_finalization_linkage and 000004_payslip_components. Four tables:
-- payroll_runs, pay_slips, pay_slip_items, shadow_payroll_comparisons.
--
-- Depends on 0022 and 0024: the service resolves each employee through
-- employee-master-svc, takes the base salary from employment-contracts-svc, and
-- reads the component composition from compensation-svc.
--
-- ── What 000004 added, and why ───────────────────────────────────────────────
-- A pay slip recorded four totals and nothing else, so nobody could answer "why
-- is my net pay this number". The lines behind the totals now come from
-- compensation-svc's breakdown endpoint and are stored with the slip that used
-- them.
--
-- ── The lines are copied, not referenced ─────────────────────────────────────
-- pay_slip_items carries calculation_method and calculation_value rather than
-- pointing at compensation.structure_components. If a structure changes 40% HRA
-- to 35% next quarter, this payslip must still show the 40% it was actually
-- paid on. A foreign key would make the slip re-read as whatever the structure
-- says today, which is the opposite of what a payslip is for.
--
-- That is also why this schema holds no FK into `compensation` at all:
-- structure_id is recorded as a plain UUID, an audit trail of which structure
-- was used, not a live join.
--
-- ── Finalized runs are immutable ─────────────────────────────────────────────
-- Two triggers below refuse UPDATE and DELETE of a COMPLETED run, and of any
-- slip belonging to one. A trigger rather than a grant or a policy because it
-- binds even a BYPASSRLS role such as Supabase's service_role, which neither of
-- those does.
--
-- They are service-local functions rather than the shared app.reject_mutation()
-- because these tables are not append-only: a run is updated repeatedly while it
-- is being calculated, and its slips are cleared and re-derived on every
-- recalculation. Only mutation AFTER finalization is refused, which is a
-- conditional the shared function does not express.

CREATE SCHEMA IF NOT EXISTS payroll_run;

COMMENT ON SCHEMA payroll_run IS
    'payroll-run-svc. Payroll runs, the payslips they produced and the lines behind each payslip. A COMPLETED run and its slips are immutable, enforced by trigger.';

GRANT USAGE ON SCHEMA payroll_run TO zoiko_backend, authenticated;

-- ── payroll_runs ─────────────────────────────────────────────────────────────

CREATE TABLE payroll_run.payroll_runs (
    run_id                 UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id              VARCHAR(255) NOT NULL,
    legal_entity_id        VARCHAR(255) NOT NULL,

    run_number             VARCHAR(100) NOT NULL,
    pay_period_start       DATE         NOT NULL,
    pay_period_end         DATE         NOT NULL,
    pay_date               DATE         NOT NULL,

    -- INITIATED | CALCULATED | BLOCKED | COMPLETED
    status                 VARCHAR(50)  NOT NULL,
    is_shadow_run          BOOLEAN      NOT NULL DEFAULT false,

    total_gross_pay        NUMERIC(18, 4) NOT NULL DEFAULT 0,
    total_net_pay          NUMERIC(18, 4) NOT NULL DEFAULT 0,
    total_tax_deductions   NUMERIC(18, 4) NOT NULL DEFAULT 0,
    total_other_deductions NUMERIC(18, 4) NOT NULL DEFAULT 0,
    employee_count         INT          NOT NULL DEFAULT 0,

    correlation_id         VARCHAR(255) NOT NULL DEFAULT '',

    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    finalized_at           TIMESTAMPTZ,

    -- Populated only when the caller finalizing the run supplies one; no
    -- fabricated value when none exists yet.
    governance_decision_id TEXT,
    -- Computed by the service over the run's own locked totals at the moment of
    -- finalization — not invented, not caller-supplied.
    snapshot_hash          TEXT,

    CONSTRAINT payroll_runs_status_known
        CHECK (status IN ('INITIATED', 'CALCULATED', 'BLOCKED', 'COMPLETED')),

    -- A pay period that ends before it starts is not a period, and the pay date
    -- cannot precede the work it pays for.
    CONSTRAINT payroll_runs_period_ordered
        CHECK (pay_period_end >= pay_period_start),
    CONSTRAINT payroll_runs_pay_date_after_period
        CHECK (pay_date >= pay_period_start),

    CONSTRAINT payroll_runs_totals_non_negative
        CHECK (total_gross_pay >= 0
           AND total_tax_deductions >= 0
           AND total_other_deductions >= 0
           AND employee_count >= 0),

    -- A COMPLETED run must record when it was finalized and the hash that makes
    -- it reproducible. Without both, "finalized" is a status with nothing behind
    -- it and an auditor has only the final numbers to trust.
    CONSTRAINT payroll_runs_completed_is_evidenced
        CHECK (
            status <> 'COMPLETED'
            OR (finalized_at IS NOT NULL AND snapshot_hash IS NOT NULL)
        ),

    CONSTRAINT payroll_runs_tenant_id_unique UNIQUE (tenant_id, run_id)
);

-- Idempotency: a retried initiate (a client timeout on a request that actually
-- succeeded) resolves to the original run instead of creating a duplicate run
-- for the same period.
CREATE UNIQUE INDEX idx_payroll_runs_tenant_correlation
    ON payroll_run.payroll_runs (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_payroll_runs_tenant_entity
    ON payroll_run.payroll_runs (tenant_id, legal_entity_id);
CREATE INDEX idx_payroll_runs_tenant_status
    ON payroll_run.payroll_runs (tenant_id, status);

-- ── pay_slips ────────────────────────────────────────────────────────────────

CREATE TABLE payroll_run.pay_slips (
    slip_id             UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           VARCHAR(255) NOT NULL,
    run_id              UUID         NOT NULL,

    employee_id         UUID         NOT NULL,
    employee_number     VARCHAR(100) NOT NULL,
    employee_name       VARCHAR(200) NOT NULL,

    gross_pay           NUMERIC(18, 4) NOT NULL,
    tax_withheld        NUMERIC(18, 4) NOT NULL,
    benefits_deductions NUMERIC(18, 4) NOT NULL,
    net_pay             NUMERIC(18, 4) NOT NULL,

    currency            VARCHAR(3)   NOT NULL,
    effective_date      DATE         NOT NULL,

    -- The base tax was actually applied to. Not the same as gross: non-taxable
    -- earnings are excluded and taxable deductions come off it.
    taxable_amount      NUMERIC(18, 4) NOT NULL DEFAULT 0,

    -- The compensation structure this slip was computed from. Nullable: an
    -- employee paid a flat base salary has none, which is a valid state rather
    -- than missing data. Deliberately not a foreign key — see the header.
    structure_id        UUID,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- A slip in one tenant against another tenant's run is unrepresentable.
    -- The single-column reference in 000001 accepted it.
    CONSTRAINT pay_slips_run_same_tenant
        FOREIGN KEY (tenant_id, run_id)
        REFERENCES payroll_run.payroll_runs (tenant_id, run_id) ON DELETE CASCADE,

    -- Gross, tax and deductions are quantities. Net is not: deductions can
    -- legitimately exceed pay — an advance recovery, say — and reporting that
    -- as anything other than negative would hide it from the payroll manager
    -- who has to act on it.
    CONSTRAINT pay_slips_amounts_non_negative
        CHECK (gross_pay >= 0
           AND tax_withheld >= 0
           AND benefits_deductions >= 0
           AND taxable_amount >= 0),

    -- Tax cannot be withheld on more than the whole gross.
    CONSTRAINT pay_slips_taxable_within_gross
        CHECK (taxable_amount <= gross_pay),

    CONSTRAINT pay_slips_tenant_id_unique UNIQUE (tenant_id, slip_id)
);

CREATE INDEX idx_pay_slips_tenant_run
    ON payroll_run.pay_slips (tenant_id, run_id);
CREATE INDEX idx_pay_slips_tenant_emp
    ON payroll_run.pay_slips (tenant_id, employee_id);

-- ── pay_slip_items ───────────────────────────────────────────────────────────

CREATE TABLE payroll_run.pay_slip_items (
    item_id            UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id          VARCHAR(255) NOT NULL,
    slip_id            UUID         NOT NULL,

    -- Which catalogue component this came from, for tracing. Not a foreign key
    -- into `compensation`: the component may be retired later, and this line
    -- must keep reading the same either way.
    component_id       UUID,

    component_code     VARCHAR(50)  NOT NULL,
    component_name     VARCHAR(150) NOT NULL,
    -- EARNING | DEDUCTION
    component_type     VARCHAR(20)  NOT NULL,
    is_taxable         BOOLEAN      NOT NULL DEFAULT true,

    -- FIXED | PERCENT_OF_BASE — copied, so the slip shows the derivation it was
    -- actually paid on rather than whatever the structure says today.
    calculation_method VARCHAR(30)  NOT NULL,
    calculation_value  NUMERIC(18, 4) NOT NULL,

    amount             NUMERIC(18, 4) NOT NULL,
    sequence           INTEGER      NOT NULL DEFAULT 0,

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pay_slip_items_slip_same_tenant
        FOREIGN KEY (tenant_id, slip_id)
        REFERENCES payroll_run.pay_slips (tenant_id, slip_id) ON DELETE CASCADE,

    CONSTRAINT pay_slip_items_type_check
        CHECK (component_type IN ('EARNING', 'DEDUCTION')),
    CONSTRAINT pay_slip_items_method_check
        CHECK (calculation_method IN ('FIXED', 'PERCENT_OF_BASE')),
    CONSTRAINT pay_slip_items_amount_check
        CHECK (amount >= 0),
    CONSTRAINT pay_slip_items_value_check
        CHECK (calculation_value >= 0),
    CONSTRAINT pay_slip_items_percent_range_check
        CHECK (calculation_method <> 'PERCENT_OF_BASE' OR calculation_value <= 100),

    -- One line per component per slip.
    CONSTRAINT pay_slip_items_unique UNIQUE (slip_id, component_code)
);

-- Lines are always read for one slip, in payslip order.
CREATE INDEX idx_pay_slip_items_slip
    ON payroll_run.pay_slip_items (tenant_id, slip_id, sequence);

-- ── shadow_payroll_comparisons ───────────────────────────────────────────────

CREATE TABLE payroll_run.shadow_payroll_comparisons (
    comparison_id       UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id           VARCHAR(255) NOT NULL,
    run_id              UUID         NOT NULL,
    employee_id         UUID         NOT NULL,

    legacy_gross_pay    NUMERIC(18, 4) NOT NULL,
    legacy_net_pay      NUMERIC(18, 4) NOT NULL,
    legacy_tax_withheld NUMERIC(18, 4) NOT NULL,

    zoiko_gross_pay     NUMERIC(18, 4) NOT NULL,
    zoiko_net_pay       NUMERIC(18, 4) NOT NULL,
    zoiko_tax_withheld  NUMERIC(18, 4) NOT NULL,

    gross_variance      NUMERIC(18, 4) NOT NULL,
    net_variance        NUMERIC(18, 4) NOT NULL,
    tax_variance        NUMERIC(18, 4) NOT NULL,
    is_equivalent       BOOLEAN      NOT NULL,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT shadow_comparisons_run_same_tenant
        FOREIGN KEY (tenant_id, run_id)
        REFERENCES payroll_run.payroll_runs (tenant_id, run_id) ON DELETE CASCADE
);

CREATE INDEX idx_shadow_comp_tenant_run
    ON payroll_run.shadow_payroll_comparisons (tenant_id, run_id);

-- ── Finalized runs are immutable ─────────────────────────────────────────────

CREATE OR REPLACE FUNCTION payroll_run.reject_finalized_run_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- On UPDATE, OLD is the row as it stands. A run may be updated freely up to
    -- the moment it completes; the transition INTO COMPLETED is itself an
    -- update of a not-yet-completed row, so it passes.
    IF OLD.status = 'COMPLETED' THEN
        RAISE EXCEPTION
            'payroll run % is finalized and immutable: % is not permitted',
            OLD.run_id, TG_OP;
    END IF;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION payroll_run.reject_finalized_run_mutation() IS
    'Refuses UPDATE and DELETE of a COMPLETED payroll run. A trigger rather than a grant or policy because it binds even a BYPASSRLS role such as service_role.';

CREATE TRIGGER payroll_runs_finalized_immutable
    BEFORE UPDATE OR DELETE ON payroll_run.payroll_runs
    FOR EACH ROW
    EXECUTE FUNCTION payroll_run.reject_finalized_run_mutation();

CREATE OR REPLACE FUNCTION payroll_run.reject_finalized_slip_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    run_status VARCHAR(50);
BEGIN
    SELECT status INTO run_status
    FROM payroll_run.payroll_runs
    WHERE run_id = OLD.run_id;

    IF run_status = 'COMPLETED' THEN
        RAISE EXCEPTION
            'pay slip % belongs to finalized run %: % is not permitted',
            OLD.slip_id, OLD.run_id, TG_OP;
    END IF;
    RETURN NEW;
END;
$$;

COMMENT ON FUNCTION payroll_run.reject_finalized_slip_mutation() IS
    'Refuses UPDATE and DELETE of a pay slip belonging to a COMPLETED run. Recalculation deletes and reinserts slips, which must stop once the run is finalized.';

CREATE TRIGGER pay_slips_finalized_immutable
    BEFORE UPDATE OR DELETE ON payroll_run.pay_slips
    FOR EACH ROW
    EXECUTE FUNCTION payroll_run.reject_finalized_slip_mutation();

-- ── Row-level security ───────────────────────────────────────────────────────

ALTER TABLE payroll_run.payroll_runs               ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_run.payroll_runs               FORCE  ROW LEVEL SECURITY;
ALTER TABLE payroll_run.pay_slips                  ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_run.pay_slips                  FORCE  ROW LEVEL SECURITY;
ALTER TABLE payroll_run.pay_slip_items             ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_run.pay_slip_items             FORCE  ROW LEVEL SECURITY;
ALTER TABLE payroll_run.shadow_payroll_comparisons ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_run.shadow_payroll_comparisons FORCE  ROW LEVEL SECURITY;

CREATE POLICY tenant_isolation ON payroll_run.payroll_runs
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON payroll_run.pay_slips
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON payroll_run.pay_slip_items
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON payroll_run.shadow_payroll_comparisons
    FOR ALL TO zoiko_backend
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

-- A payslip is addressed to one person, so the read is scoped to that person
-- rather than to the tenant. This is the same shape as notification-svc's
-- recipient_read and for the same reason.
--
-- It depends on app.current_principal_id() being the employee_id, which is only
-- true once identity-context principals carry it. Until then this policy
-- matches nothing, which fails closed — nobody reads a payslip they should not.
CREATE POLICY own_payslip_read ON payroll_run.pay_slips
    FOR SELECT TO authenticated
    USING (
        tenant_id = app.current_tenant_id()
        AND employee_id::text = app.current_principal_id()
    );

CREATE POLICY own_payslip_items_read ON payroll_run.pay_slip_items
    FOR SELECT TO authenticated
    USING (
        tenant_id = app.current_tenant_id()
        AND EXISTS (
            SELECT 1 FROM payroll_run.pay_slips s
            WHERE s.slip_id = pay_slip_items.slip_id
              AND s.tenant_id = pay_slip_items.tenant_id
              AND s.employee_id::text = app.current_principal_id()
        )
    );

-- ── Grants ───────────────────────────────────────────────────────────────────

-- No DELETE on payroll_runs: a run is the record that payroll was executed for
-- a period, including one that was blocked.
GRANT SELECT, INSERT, UPDATE ON payroll_run.payroll_runs TO zoiko_backend;

-- Slips, their lines and shadow comparisons DO take DELETE: recalculating a run
-- clears and re-derives them inside one transaction. The triggers above stop
-- that once the run is COMPLETED, which is the point at which the numbers stop
-- being provisional.
GRANT SELECT, INSERT, UPDATE, DELETE ON payroll_run.pay_slips                  TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE, DELETE ON payroll_run.pay_slip_items             TO zoiko_backend;
GRANT SELECT, INSERT, UPDATE, DELETE ON payroll_run.shadow_payroll_comparisons TO zoiko_backend;

GRANT SELECT ON payroll_run.pay_slips      TO authenticated;
GRANT SELECT ON payroll_run.pay_slip_items TO authenticated;


-- ============================================================================
-- FILE: 0026_policies_apply_to_connecting_role.sql
-- ============================================================================

-- 0026_policies_apply_to_connecting_role.sql
-- Platform-wide correction. Creates no tables.
--
-- ── The defect ───────────────────────────────────────────────────────────────
--
-- Every tenant policy in 0001-0025 is written `FOR ALL TO zoiko_backend`, and
-- the services do not connect as zoiko_backend. deployments/supabase creates a
-- role per service — app_identity_context, app_employee_master and so on — and
-- docker-compose.supabase.yml points each service's DB_USER at its own.
--
-- A policy names the roles it applies to. With FORCE ROW LEVEL SECURITY and no
-- policy applicable to the connecting role, that role reads zero rows and
-- writes nothing. Verified: as app_employee_master the register returned
-- `(0 rows)` and an INSERT failed with "new row violates row-level security
-- policy" — for a row in its own tenant, in its own schema.
--
-- ── Why the obvious fix is worse ─────────────────────────────────────────────
--
-- GRANT zoiko_backend TO app_employee_master makes the policy match. It also
-- hands over everything zoiko_backend holds, and every migration grants that
-- role USAGE and DML on its own schema — so zoiko_backend accumulates access to
-- all 25. Verified: with that membership, app_employee_master read
-- payroll_run.pay_slips and inserted a row into it. Tenant isolation survived;
-- SERVICE isolation did not, and "USAGE on its own schema only" is the property
-- the role-per-service design exists to provide.
--
-- ── The fix ──────────────────────────────────────────────────────────────────
--
-- Drop the role restriction. A policy with no TO clause applies to every role,
-- and isolation comes from the grants that were already there: a role holds
-- USAGE on one schema and DML on that schema's tables, so it cannot reach
-- another service's tables whatever the policy says.
--
-- Verified on the same probe: own schema readable, a write to another tenant
-- refused by the policy, and a read of another service's schema refused with
-- "permission denied for schema payroll_run" — at the grant layer, before RLS
-- is consulted at all.
--
-- Widening to PUBLIC does not expose anything to `anon`. Table privileges are
-- checked before row security, and no migration grants anon anything, so anon
-- is refused at the ACL layer and never reaches a policy.
--
-- ── Why this is generated rather than written out ────────────────────────────
--
-- 58 policies name zoiko_backend across 25 files, plus 4 that name it alongside
-- `authenticated`. Transcribing 62 DROP/CREATE pairs by hand invites exactly one
-- typo in exactly one USING clause, which would silently widen a tenant
-- boundary. Reading each policy's own expression out of pg_policies and putting
-- it back verbatim cannot drift from what was reviewed.
--
-- The 38 policies that name ONLY `authenticated` are left alone. Those are the
-- deliberate console-session reads — a recipient reading their own notification,
-- an employee reading the holiday calendar — and they are correctly restricted.

-- ── 1. Policies apply to the connecting role ─────────────────────────────────

DO $$
DECLARE
    p        record;
    stmt     text;
    changed  int := 0;
BEGIN
    FOR p IN
        SELECT schemaname, tablename, policyname, cmd, qual, with_check
          FROM pg_policies
         WHERE 'zoiko_backend' = ANY (roles)
         ORDER BY schemaname, tablename, policyname
    LOOP
        EXECUTE format('DROP POLICY %I ON %I.%I',
                       p.policyname, p.schemaname, p.tablename);

        -- cmd comes from the catalogue as ALL | SELECT | INSERT | UPDATE |
        -- DELETE, so it is a keyword rather than anything caller-supplied.
        stmt := format('CREATE POLICY %I ON %I.%I FOR %s',
                       p.policyname, p.schemaname, p.tablename, p.cmd);

        -- qual is NULL for an INSERT-only policy and with_check is NULL for a
        -- SELECT or DELETE one. Emitting only what was there keeps each policy
        -- legal for its own command without a per-command branch.
        IF p.qual IS NOT NULL THEN
            stmt := stmt || format(' USING (%s)', p.qual);
        END IF;
        IF p.with_check IS NOT NULL THEN
            stmt := stmt || format(' WITH CHECK (%s)', p.with_check);
        END IF;

        EXECUTE stmt;
        changed := changed + 1;
    END LOOP;

    RAISE NOTICE 'policies rewritten to apply to the connecting role: %', changed;
END
$$;

-- ── 2. Every service role can call the identity helpers ──────────────────────
--
-- A policy expression is evaluated as the querying role, so a role that now
-- matches the policy must also be able to run app.current_tenant_id(). 0001
-- granted that to zoiko_backend, authenticated and anon only.
--
-- Guarded on the role existing: on a fresh project the migrations run before
-- deployments/supabase creates the roles, and a missing one must not abort the
-- batch. deployments/supabase performs the same grants, so a later run of it
-- covers roles created after this migration.

DO $$
DECLARE
    r       text;
    granted int := 0;
BEGIN
    FOREACH r IN ARRAY ARRAY[
        'app_identity_context',
        'app_tenant_entity_registry',
        'app_authorization',
        'app_governance_decision_log',
        'app_access_control',
        'app_employee_master',
        'app_leave_absence',
        'app_compensation',
        'app_payroll_run'
    ]
    LOOP
        IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
            CONTINUE;
        END IF;

        EXECUTE format('GRANT USAGE ON SCHEMA app TO %I', r);
        EXECUTE format('GRANT EXECUTE ON FUNCTION app.current_tenant_id() TO %I', r);
        EXECUTE format('GRANT EXECUTE ON FUNCTION app.current_principal_id() TO %I', r);

        -- Undo the membership if it was granted as a workaround for the defect
        -- this migration fixes. It is what carried cross-service access, and it
        -- is no longer needed for the policy to apply.
        --
        -- Left INHERIT: it is harmless with no memberships, and a role that is
        -- NOINHERIT while holding one would need an explicit SET ROLE per
        -- session, which no service issues.
        EXECUTE format('REVOKE zoiko_backend FROM %I', r);

        granted := granted + 1;
    END LOOP;

    RAISE NOTICE 'service roles granted the identity helpers: %', granted;
END
$$;

-- ── 3. Verification ──────────────────────────────────────────────────────────
--
-- Fails the migration if any policy still carries a role restriction naming
-- zoiko_backend. Cheaper to find here than as an empty register in a service.

DO $$
DECLARE leftover int;
BEGIN
    SELECT count(*) INTO leftover
      FROM pg_policies
     WHERE 'zoiko_backend' = ANY (roles);

    IF leftover > 0 THEN
        RAISE EXCEPTION
            '% policies still restricted to zoiko_backend; the rewrite did not complete',
            leftover;
    END IF;
END
$$;
