-- ============================================================================
-- Zoiko Suite — Supabase migrations 0030 to 0030.
--
-- Generated by supabase/build-delta.sh from supabase/migrations/*.sql.
-- Do not hand-edit: change the per-service migration and regenerate.
--
-- A DELTA, for a project that already has the earlier migrations applied.
-- For a fresh project use zoiko-suite-all.sql instead — this file assumes
-- 0001_platform_foundation has already created:
--
--   - the zoiko_backend role
--   - the app schema, app.current_tenant_id() and app.current_principal_id()
--
-- Verify what is already applied before pasting this:
--
--   SELECT nspname FROM pg_namespace
--    WHERE nspname NOT LIKE 'pg_%'
--      AND nspname NOT IN ('information_schema','public')
--    ORDER BY 1;
--
-- Every CREATE below is bare, not IF NOT EXISTS, on purpose: if something here
-- already exists the batch must abort so you can look at why, rather than skip
-- it and leave the schema half-migrated.
-- ============================================================================



-- ============================================================================
-- FILE: 0030_employment_contracts_svc.sql
-- ============================================================================

-- 0030_employment_contracts_svc.sql
-- employment-contracts-svc → schema `employment_contracts`
--
-- Squashed end state of 000001_initial_schema and 000002_add_idempotency.
-- Two tables: employment_contracts, contract_amendments.
--
-- ── Why this service, and why now ────────────────────────────────────────────
--
-- 0022-0025 brought the HR domain onto Supabase and stopped one step short.
-- payroll-run-svc resolves every payslip from compensation-svc, but it reaches
-- that call only after confirming an active salary contract for each employee:
--
--     if len(missingContracts) > 0 { ... return }   // handler.go
--     bd, err := h.compClient.GetBreakdown(..., contracts[emp.EmployeeID].BaseSalaryAmount)
--
-- The base amount the breakdown is resolved against IS the contract's, so the
-- compensation call cannot run before contracts do. With this service absent
-- from Supabase, every payroll calculation there ends at 422
-- contract_lookup_failed and the compensation path — written, wired, and
-- covered by tests — has never executed against the real database.
--
-- This migration is what makes that path reachable. It is the fifth and last
-- service the HR domain needs.
--
-- ── What changes relative to the service's own migration ─────────────────────
--
-- The service's 000001 is the compose-estate schema, and it carries the two
-- defects the README names as the reason this move is worth making:
--
--   ENABLE without FORCE. The estate's recurring defect — a policy that is
--   present, correct, and never executed. Every table here gets both.
--
--   USING without WITH CHECK. USING governs what is visible; WITH CHECK governs
--   what may be written. With only USING, a caller can insert a contract into
--   another tenant that it then cannot see. Both policies below carry both.
--
-- It also reads `current_setting('app.tenant_id', true)` directly. That works
-- only for a service calling set_config, and says nothing for a PostgREST
-- caller carrying a JWT. app.current_tenant_id() resolves either.
--
-- ── Policies carry no TO clause ──────────────────────────────────────────────
--
-- 0026 removed the role restriction from all 62 policies that named
-- zoiko_backend, because the services connect as app_<service>, not as
-- zoiko_backend, and a policy that names roles applies to those roles only —
-- under FORCE that means zero rows read and nothing written. This migration
-- runs after 0026, so writing `TO zoiko_backend` here would reintroduce exactly
-- what that file repaired, in the one schema it could not have covered.
--
-- Isolation comes from the grants instead: app_employment_contracts holds USAGE
-- on this schema alone.

CREATE SCHEMA IF NOT EXISTS employment_contracts;

COMMENT ON SCHEMA employment_contracts IS
    'employment-contracts-svc. The authoritative base salary and its effective-dated version history. payroll-run-svc fails closed without it, and resolves every compensation breakdown against the base amount held here.';

GRANT USAGE ON SCHEMA employment_contracts TO zoiko_backend, authenticated;

-- ── employment_contracts ─────────────────────────────────────────────────────

CREATE TABLE employment_contracts.employment_contracts (
    contract_id        UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id          VARCHAR(255) NOT NULL,
    legal_entity_id    VARCHAR(255) NOT NULL,
    employee_id        UUID         NOT NULL,

    contract_number    VARCHAR(100) NOT NULL,
    version            INT          NOT NULL DEFAULT 1,

    -- FULL_TIME | PART_TIME | FIXED_TERM | EXECUTIVE
    contract_type      VARCHAR(50)  NOT NULL,
    -- DRAFT | ACTIVE | SUPERSEDED | TERMINATED | EXPIRED
    status             VARCHAR(50)  NOT NULL,

    title              VARCHAR(150) NOT NULL,
    base_salary_amount NUMERIC(18, 4) NOT NULL,
    currency           VARCHAR(3)   NOT NULL,
    -- MONTHLY | BIWEEKLY | WEEKLY
    pay_frequency      VARCHAR(50)  NOT NULL,

    effective_from     DATE         NOT NULL,
    effective_to       DATE,

    document_vault_ref VARCHAR(255),

    -- Idempotency key for IssueContract. NOT NULL DEFAULT '' rather than
    -- nullable because the service's ON CONFLICT targets the partial index
    -- below, and '' is how it spells "this caller sent no key".
    correlation_id     VARCHAR(255) NOT NULL DEFAULT '',

    created_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- The vocabularies the domain defines. They live in a Go comment on
    -- domain.EmploymentContract and nowhere else today, so any other writer —
    -- a migration, a console, the service_role key — could leave a value no
    -- consumer knows how to read. payroll-run-svc filters on status = 'ACTIVE'
    -- to find the salary it pays; a row whose status is misspelled is a salary
    -- that silently stops being paid.
    CONSTRAINT contracts_type_known
        CHECK (contract_type IN ('FULL_TIME', 'PART_TIME', 'FIXED_TERM', 'EXECUTIVE')),
    CONSTRAINT contracts_status_known
        CHECK (status IN ('DRAFT', 'ACTIVE', 'SUPERSEDED', 'TERMINATED', 'EXPIRED')),
    CONSTRAINT contracts_pay_frequency_known
        CHECK (pay_frequency IN ('MONTHLY', 'BIWEEKLY', 'WEEKLY')),

    -- The handler already refuses base_salary_amount <= 0 on issue. It does not
    -- re-check it on amend, where the figure is caller-supplied and optional,
    -- so a negative salary could reach the table by that path alone.
    CONSTRAINT contracts_salary_positive
        CHECK (base_salary_amount > 0),

    -- ISO 4217, which is what every consumer assumes when it renders an amount.
    CONSTRAINT contracts_currency_iso
        CHECK (currency ~ '^[A-Z]{3}$'),

    -- A contract cannot end before it began. AmendContract closes the prior
    -- version by setting effective_to to the amendment's effective_from, so
    -- without this a backdated amendment leaves a negative-length contract.
    CONSTRAINT contracts_effective_range
        CHECK (effective_to IS NULL OR effective_to >= effective_from),

    CONSTRAINT contracts_version_positive
        CHECK (version >= 1),

    -- The target of the composite foreign key from contract_amendments.
    CONSTRAINT contracts_tenant_id_unique UNIQUE (tenant_id, contract_id)
);

-- Version history is resolved by contract_number:
--
--     SELECT ... WHERE tenant_id = $1 AND contract_number = $2 ORDER BY version
--
-- so every row sharing a number is presented as a version of one contract. Two
-- rows claiming the same version of the same number make that history
-- ambiguous, and AmendContract — which writes version = old + 1 — has no way to
-- discover it happened. contract_number is caller-supplied on issue, so nothing
-- upstream prevents it.
CREATE UNIQUE INDEX idx_contracts_tenant_number_version
    ON employment_contracts.employment_contracts (tenant_id, contract_number, version);

-- Idempotency. This index is what the service's ON CONFLICT names:
--
--     ON CONFLICT (tenant_id, correlation_id) WHERE correlation_id != '' DO NOTHING
--
-- The predicate has to match this one for the inference to resolve, so the two
-- are a pair — changing either alone turns a retried IssueContract back into a
-- duplicate contract. Partial because the many rows carrying no key must not
-- collide with each other.
CREATE UNIQUE INDEX idx_contracts_tenant_correlation
    ON employment_contracts.employment_contracts (tenant_id, correlation_id)
    WHERE correlation_id <> '';

CREATE INDEX idx_contracts_tenant_employee
    ON employment_contracts.employment_contracts (tenant_id, employee_id);
CREATE INDEX idx_contracts_tenant_status
    ON employment_contracts.employment_contracts (tenant_id, status);
CREATE INDEX idx_contracts_tenant_entity
    ON employment_contracts.employment_contracts (tenant_id, legal_entity_id);

-- The payroll hot path. A payroll run calls
-- GET /v1/contracts/employee/{id}/active once per employee, which is
--
--     WHERE tenant_id = $1 AND employee_id = $2 AND status = 'ACTIVE'
--     ORDER BY version DESC LIMIT 1
--
-- Without this, a 500-employee run is 500 scans of the tenant's whole contract
-- history.
CREATE INDEX idx_contracts_active_by_employee
    ON employment_contracts.employment_contracts (tenant_id, employee_id, version DESC)
    WHERE status = 'ACTIVE';

-- ── contract_amendments ──────────────────────────────────────────────────────
--
-- The audit log of why a salary changed. Append-only: an amendment is the
-- evidence for a pay change, and a pay change whose stated reason can be edited
-- afterwards is not evidence of anything.

CREATE TABLE employment_contracts.contract_amendments (
    amendment_id     UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id        VARCHAR(255) NOT NULL,
    contract_id      UUID         NOT NULL,

    from_version     INT          NOT NULL,
    to_version       INT          NOT NULL,

    amendment_reason TEXT         NOT NULL,
    amended_by       VARCHAR(255) NOT NULL,
    effective_from   DATE         NOT NULL,

    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    -- An amendment moves a contract forward. Equal or descending versions would
    -- describe a rollback, which the service has no operation for and no
    -- consumer would read correctly.
    CONSTRAINT amendments_version_advances
        CHECK (to_version > from_version),

    CONSTRAINT amendments_from_version_positive
        CHECK (from_version >= 1),

    -- An amendment belonging to another tenant's contract is unrepresentable.
    -- The single-column form the service's own migration uses would have
    -- accepted one: nothing made the referenced contract's tenant agree with
    -- the amendment's, and the two are written from separate parameters in
    -- AmendContract.
    CONSTRAINT amendments_contract_same_tenant
        FOREIGN KEY (tenant_id, contract_id)
        REFERENCES employment_contracts.employment_contracts (tenant_id, contract_id)
);

CREATE INDEX idx_amendments_tenant_contract
    ON employment_contracts.contract_amendments (tenant_id, contract_id);

CREATE TRIGGER contract_amendments_append_only
    BEFORE UPDATE OR DELETE ON employment_contracts.contract_amendments
    FOR EACH ROW EXECUTE FUNCTION app.reject_mutation();

COMMENT ON TRIGGER contract_amendments_append_only
    ON employment_contracts.contract_amendments IS
    'A pay change''s stated reason is evidence. Withholding UPDATE/DELETE stops zoiko_backend; this trigger also binds a BYPASSRLS role such as Supabase''s service_role.';

-- ── Row-level security ───────────────────────────────────────────────────────

ALTER TABLE employment_contracts.employment_contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE employment_contracts.employment_contracts FORCE  ROW LEVEL SECURITY;
ALTER TABLE employment_contracts.contract_amendments  ENABLE ROW LEVEL SECURITY;
ALTER TABLE employment_contracts.contract_amendments  FORCE  ROW LEVEL SECURITY;

-- No TO clause: see the header. Fails closed on a missing tenant by SQL
-- semantics — app.current_tenant_id() is NULL with no identity installed, and
-- `tenant_id = NULL` is NULL, which is not true.
CREATE POLICY tenant_isolation ON employment_contracts.employment_contracts
    FOR ALL
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

CREATE POLICY tenant_isolation ON employment_contracts.contract_amendments
    FOR ALL
    USING      (tenant_id = app.current_tenant_id())
    WITH CHECK (tenant_id = app.current_tenant_id());

-- ── Grants ───────────────────────────────────────────────────────────────────

-- No DELETE on contracts: a contract is the basis of every payslip calculated
-- from it. Ending one is a status change to TERMINATED with effective_to set,
-- which is what TerminateContract does.
GRANT SELECT, INSERT, UPDATE ON employment_contracts.employment_contracts TO zoiko_backend;

-- No UPDATE and no DELETE on the log. The service only ever inserts.
GRANT SELECT, INSERT ON employment_contracts.contract_amendments TO zoiko_backend;

-- ── The service's own login role ─────────────────────────────────────────────
--
-- Same shape as 0026 section 2: a policy expression is evaluated as the
-- querying role, so app_employment_contracts must be able to call
-- app.current_tenant_id() or every policy above raises instead of filtering.
--
-- Guarded on the role existing. On a fresh project the migrations run before
-- deployments/supabase creates the roles, and a missing one must not abort the
-- batch; that tool performs the same grants on a later run.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_employment_contracts') THEN
        GRANT USAGE ON SCHEMA app TO app_employment_contracts;
        GRANT EXECUTE ON FUNCTION app.current_tenant_id()    TO app_employment_contracts;
        GRANT EXECUTE ON FUNCTION app.current_principal_id() TO app_employment_contracts;

        GRANT USAGE ON SCHEMA employment_contracts TO app_employment_contracts;
        GRANT SELECT, INSERT, UPDATE
            ON employment_contracts.employment_contracts TO app_employment_contracts;
        GRANT SELECT, INSERT
            ON employment_contracts.contract_amendments  TO app_employment_contracts;

        RAISE NOTICE 'app_employment_contracts granted its schema and the identity helpers';
    ELSE
        RAISE NOTICE 'role app_employment_contracts absent; deployments/supabase will grant it';
    END IF;
END
$$;

-- ── Verification ─────────────────────────────────────────────────────────────
--
-- Proves the properties this migration exists for, rather than asserting them:
-- both tables forced, both policies carrying WITH CHECK, the idempotency index
-- actually inferrable by the service's ON CONFLICT, and tenant isolation
-- binding in both directions.
--
-- The isolation probe runs as zoiko_backend rather than as the applying role.
-- Migrations are applied by a superuser, and a superuser bypasses row security
-- unconditionally — asserting isolation from here without switching role would
-- test nothing and fail. zoiko_backend is the NOSUPERUSER NOBYPASSRLS role 0001
-- creates for exactly this reason. Skipped, not failed, where the applying role
-- cannot assume it.

DO $$
DECLARE
    unprotected int;
    no_check    int;
    ten_a       TEXT := 'zzz-0030-tenant-a';
    ten_b       TEXT := 'zzz-0030-tenant-b';
    emp         UUID := gen_random_uuid();
    c1          UUID := gen_random_uuid();
    inserted    int;
    leaked      int;
    refused     boolean := false;
BEGIN
    -- 1. Both tables enabled AND forced.
    SELECT count(*) INTO unprotected
      FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'employment_contracts' AND c.relkind = 'r'
       AND NOT (c.relrowsecurity AND c.relforcerowsecurity);
    IF unprotected > 0 THEN
        RAISE EXCEPTION '% employment_contracts tables lack forced row security', unprotected;
    END IF;

    -- 2. Every policy governs writes as well as reads.
    SELECT count(*) INTO no_check
      FROM pg_policies
     WHERE schemaname = 'employment_contracts' AND with_check IS NULL;
    IF no_check > 0 THEN
        RAISE EXCEPTION '% employment_contracts policies have no WITH CHECK', no_check;
    END IF;

    -- 3. Idempotency. The second INSERT is the retry the service performs
    --    verbatim; if the ON CONFLICT cannot infer this index the statement
    --    errors rather than resolving to the original row.
    PERFORM set_config('app.tenant_id', ten_a, true);

    INSERT INTO employment_contracts.employment_contracts
        (contract_id, tenant_id, legal_entity_id, employee_id, contract_number,
         version, contract_type, status, title, base_salary_amount, currency,
         pay_frequency, effective_from, correlation_id)
    VALUES (c1, ten_a, 'le-verify', emp, 'VERIFY-0030',
            1, 'FULL_TIME', 'ACTIVE', 'Verification', 1000, 'USD',
            'MONTHLY', '2026-01-01', 'corr-0030');

    INSERT INTO employment_contracts.employment_contracts
        (contract_id, tenant_id, legal_entity_id, employee_id, contract_number,
         version, contract_type, status, title, base_salary_amount, currency,
         pay_frequency, effective_from, correlation_id)
    VALUES (gen_random_uuid(), ten_a, 'le-verify', emp, 'VERIFY-0030-DUP',
            1, 'FULL_TIME', 'ACTIVE', 'Retry', 1000, 'USD',
            'MONTHLY', '2026-01-01', 'corr-0030')
    -- `!=` deliberately, which is how the service spells it. Postgres
    -- normalises it to `<>` before matching the index predicate, and this
    -- statement is the proof of that rather than an assumption about it.
    ON CONFLICT (tenant_id, correlation_id) WHERE correlation_id != '' DO NOTHING;
    GET DIAGNOSTICS inserted = ROW_COUNT;
    IF inserted <> 0 THEN
        RAISE EXCEPTION 'a retried IssueContract created a duplicate contract';
    END IF;

    -- 4 and 5. Isolation, both directions, as a role the policies apply to.
    IF NOT pg_has_role(current_user, 'zoiko_backend', 'USAGE') THEN
        RAISE NOTICE 'skipping the isolation probe: % cannot assume zoiko_backend', current_user;
    ELSE
        SET LOCAL ROLE zoiko_backend;

        -- 4. The write side is bound. Tenant A must not be able to plant a row
        --    in tenant B — the gap a USING-only policy leaves open, and the one
        --    the service's own migration still has.
        PERFORM set_config('app.tenant_id', ten_a, true);
        BEGIN
            INSERT INTO employment_contracts.employment_contracts
                (contract_id, tenant_id, legal_entity_id, employee_id, contract_number,
                 version, contract_type, status, title, base_salary_amount, currency,
                 pay_frequency, effective_from)
            VALUES (gen_random_uuid(), ten_b, 'le-verify', emp, 'VERIFY-0030-X',
                    1, 'FULL_TIME', 'ACTIVE', 'Cross tenant', 1000, 'USD',
                    'MONTHLY', '2026-01-01');
        EXCEPTION WHEN insufficient_privilege THEN
            refused := true;
        END;

        -- A failed subtransaction rolls back the SET LOCAL ROLE with it, so
        -- re-establish it rather than assuming it survived the handler.
        SET LOCAL ROLE zoiko_backend;

        IF NOT refused THEN
            RAISE EXCEPTION 'a tenant-scoped connection wrote a row into another tenant';
        END IF;

        -- 5. The read side is bound too.
        PERFORM set_config('app.tenant_id', ten_b, true);
        SELECT count(*) INTO leaked
          FROM employment_contracts.employment_contracts
         WHERE contract_number LIKE 'VERIFY-0030%';
        IF leaked <> 0 THEN
            RAISE EXCEPTION 'tenant B read % of tenant A''s contracts', leaked;
        END IF;

        RESET ROLE;
    END IF;

    -- 6. Clean up. Contracts carry no DELETE grant for zoiko_backend, so this
    --    runs after RESET ROLE, as the applying role.
    DELETE FROM employment_contracts.employment_contracts
     WHERE contract_number LIKE 'VERIFY-0030%';
    PERFORM set_config('app.tenant_id', '', true);

    RAISE NOTICE 'verified: forced RLS, WITH CHECK on every policy, idempotent issue, isolation both ways';
END
$$;
