-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE data_residency_policies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE legal_entities NO FORCE ROW LEVEL SECURITY;
ALTER TABLE entity_hierarchies NO FORCE ROW LEVEL SECURITY;
ALTER TABLE entity_jurisdiction_assignments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE tax_identity_bundles NO FORCE ROW LEVEL SECURITY;
ALTER TABLE workspaces NO FORCE ROW LEVEL SECURITY;