// Code generated by services/_contract/rollout.sh. DO NOT EDIT.
//
// Regenerate with: services/_contract/rollout.sh payroll-tax-svc

package envelope

// ServicePolicy is this service's §4 conditional-field policy.
//
// The unconditionally mandatory fields — tenant_id, actor_subject_id,
// request_id, correlation_id, source_channel — and idempotency_key on material
// writes are enforced for every service and are not expressible here.
func ServicePolicy() Policy {
	return Policy{
		ServiceName: "payroll-tax-svc",

		// §4: mandatory for entity-specific records (INV-02).
		LegalEntityID: RequiredOnWrite,

		// §4: required for governed sensitive access.
		PurposeContext: RequiredOnWrite,

		// BookID stays NotRequired despite §4 marking book_id mandatory for
		// accounting actions: REF-06 Accounting Book / Ledger Basis does not exist in
		// services/, so no book_id can be issued or validated. See rollout.sh.
		// Flip to Required once REF-06 ships.
		BookID: NotRequired,
	}
}
