-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE departments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE positions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE org_assignments NO FORCE ROW LEVEL SECURITY;