-- accounting-period-svc (REF-05) -- period instances and their state.
--
-- Every table is tenant-scoped and FORCE ROW LEVEL SECURITY (policies live in
-- this file next to each table; FORCE means the owning role is subject to them
-- too). A bare query without app.tenant_id returns ZERO rows by design.
--
-- legal_entity_id / calendar_id / calendar_version_id are TEXT: they are
-- identifiers owned by other services (org-structure, REF-04); this service
-- stores them, it does not validate their existence beyond what REF-04 returns
-- at materialisation.

CREATE TABLE IF NOT EXISTS accounting_periods (
    period_id            UUID PRIMARY KEY,                 -- UUIDv7, generated by the service
    tenant_id            TEXT NOT NULL,
    legal_entity_id      TEXT NOT NULL,
    calendar_id          TEXT NOT NULL,
    calendar_version_id  TEXT NOT NULL,
    book_scope           TEXT NOT NULL DEFAULT '',         -- opaque; empty = entity-wide (all books)
    module_scope         TEXT NOT NULL DEFAULT '',         -- empty = all modules
    period_key           TEXT NOT NULL,                    -- e.g. FY2026-P03
    fiscal_year          INTEGER NOT NULL,
    period_no            INTEGER NOT NULL,
    start_date           DATE NOT NULL,
    end_date             DATE NOT NULL,
    kind                 TEXT NOT NULL,
    state                TEXT NOT NULL DEFAULT 'OPEN',
    version              BIGINT NOT NULL DEFAULT 1,
    reopen_book_scope    TEXT,
    reopen_module_scope  TEXT,
    reopen_expires_at    TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT accounting_periods_state_known CHECK (state IN ('OPEN','SOFT_CLOSED','HARD_CLOSED','REOPEN_AUTHORIZED','RECLOSED')),
    CONSTRAINT accounting_periods_kind_known CHECK (kind IN ('NORMAL','SPECIAL')),
    CONSTRAINT accounting_periods_dates_ordered CHECK (end_date >= start_date),
    CONSTRAINT accounting_periods_version_positive CHECK (version >= 1),
    CONSTRAINT accounting_periods_key_not_empty CHECK (period_key <> ''),
    -- a reopen is always time-bound and scoped
    CONSTRAINT accounting_periods_reopen_window CHECK (
        state <> 'REOPEN_AUTHORIZED'
        OR (reopen_expires_at IS NOT NULL AND reopen_book_scope IS NOT NULL AND reopen_module_scope IS NOT NULL)),
    -- materialisation idempotency: one period per (entity, version, scope, key)
    CONSTRAINT accounting_periods_unique_instance UNIQUE (tenant_id, legal_entity_id, calendar_version_id, book_scope, module_scope, period_key)
);
CREATE INDEX IF NOT EXISTS idx_accounting_periods_gate
    ON accounting_periods (tenant_id, legal_entity_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_accounting_periods_key
    ON accounting_periods (tenant_id, legal_entity_id, period_key);
CREATE INDEX IF NOT EXISTS idx_accounting_periods_calendar
    ON accounting_periods (tenant_id, calendar_id, calendar_version_id);

ALTER TABLE accounting_periods ENABLE ROW LEVEL SECURITY;
ALTER TABLE accounting_periods FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON accounting_periods FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));

-- PeriodStateHistory: append-only (trigger in 000002). Records every transition
-- including the initial MATERIALIZE entry (from_state empty).
CREATE TABLE IF NOT EXISTS period_state_history (
    history_id            UUID PRIMARY KEY,
    tenant_id             TEXT NOT NULL,
    period_id             UUID NOT NULL REFERENCES accounting_periods (period_id),
    from_state            TEXT NOT NULL DEFAULT '',
    to_state              TEXT NOT NULL,
    command               TEXT NOT NULL,
    acc14_workflow_ref    TEXT NOT NULL DEFAULT '',
    control_snapshot_ref  TEXT NOT NULL DEFAULT '',
    requested_by          TEXT NOT NULL,
    reason                TEXT NOT NULL,
    recorded_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    expected_version      BIGINT NOT NULL,
    resulting_version     BIGINT NOT NULL,
    decision_fingerprint  TEXT NOT NULL DEFAULT '',
    reopen_book_scope     TEXT,
    reopen_module_scope   TEXT,
    reopen_expires_at     TIMESTAMPTZ,
    correlation_id        TEXT NOT NULL DEFAULT '',
    CONSTRAINT period_state_history_to_known CHECK (to_state IN ('OPEN','SOFT_CLOSED','HARD_CLOSED','REOPEN_AUTHORIZED','RECLOSED')),
    CONSTRAINT period_state_history_command_known CHECK (command IN ('MATERIALIZE','SOFT_CLOSE','HARD_CLOSE','AUTHORIZE_REOPEN','RECLOSE')),
    -- every transition after materialisation carries its ACC-14 evidence
    CONSTRAINT period_state_history_evidence CHECK (
        command = 'MATERIALIZE' OR (acc14_workflow_ref <> '' AND control_snapshot_ref <> '' AND decision_fingerprint <> ''))
);
CREATE INDEX IF NOT EXISTS idx_period_state_history_period
    ON period_state_history (tenant_id, period_id, recorded_at, history_id);
-- one workflow decision is applied to a period at most once
CREATE UNIQUE INDEX IF NOT EXISTS uq_period_state_history_decision
    ON period_state_history (period_id, decision_fingerprint) WHERE decision_fingerprint <> '';

ALTER TABLE period_state_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE period_state_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON period_state_history FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));
