-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE leave_types NO FORCE ROW LEVEL SECURITY;
ALTER TABLE leave_balances NO FORCE ROW LEVEL SECURITY;
ALTER TABLE leave_requests NO FORCE ROW LEVEL SECURITY;
ALTER TABLE holidays NO FORCE ROW LEVEL SECURITY;