package config

import (
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
)

// The DSN is assembled by string concatenation, so the only thing standing
// between a generated password and a malformed connection string is the
// quoting in quoteDSNValue. These tests parse the result with the same pgx
// function main.go uses, because a DSN that "looks right" and one pgx actually
// accepts are different claims.

func TestDSN_ParsesAndCarriesEveryField(t *testing.T) {
	cfg := DBConfig{
		Host:     "aws-0-eu-west-2.pooler.supabase.com",
		Port:     6543,
		Name:     "postgres",
		User:     "postgres.abcdefghijklmnop",
		Password: "a-simple-password",
		SSLMode:  "require",
		Schema:   "identity_context",
		Options:  "default_query_exec_mode=exec statement_cache_capacity=0",
	}

	parsed, err := pgxpool.ParseConfig(cfg.DSN())
	if err != nil {
		t.Fatalf("pgx rejected the DSN: %v\nDSN: %s", err, cfg.DSN())
	}
	if got := parsed.ConnConfig.Host; got != cfg.Host {
		t.Errorf("host: got %q, want %q", got, cfg.Host)
	}
	if got := parsed.ConnConfig.Port; got != 6543 {
		t.Errorf("port: got %d, want 6543", got)
	}
	if got := parsed.ConnConfig.User; got != cfg.User {
		t.Errorf("user: got %q, want %q", got, cfg.User)
	}
	if got := parsed.ConnConfig.Password; got != cfg.Password {
		t.Errorf("password: got %q, want %q", got, cfg.Password)
	}
	// search_path reaches Postgres as a startup runtime parameter, which is
	// what puts this service's tables in scope without touching a migration.
	if got := parsed.ConnConfig.RuntimeParams["search_path"]; got != "identity_context" {
		t.Errorf("search_path: got %q, want %q", got, "identity_context")
	}
	// Without this, pgx caches NAMED prepared statements and PgBouncer in
	// transaction mode fails intermittently under concurrency.
	if parsed.ConnConfig.StatementCacheCapacity != 0 {
		t.Errorf("statement cache: got %d, want 0", parsed.ConnConfig.StatementCacheCapacity)
	}
	if parsed.ConnConfig.TLSConfig == nil {
		t.Error("sslmode=require must produce a TLS config; Supabase refuses plaintext")
	}
}

// The regression this quoting exists for. Every one of these characters
// appears in passwords generated by managed database providers, and each of
// them terminates or corrupts an UNQUOTED keyword/value DSN.
func TestDSN_SurvivesAwkwardPasswords(t *testing.T) {
	passwords := map[string]string{
		"space":              "two words",
		"single quote":       "it's-a-password",
		"backslash":          `back\slash`,
		"trailing backslash": `ends-with\`,
		"equals sign":        "a=b",
		"both specials":      `it's\complicated`,
		"looks like a field": "x sslmode=disable",
		"empty":              "",
	}

	for name, password := range passwords {
		t.Run(name, func(t *testing.T) {
			cfg := DBConfig{
				Host: "db.example.supabase.co", Port: 5432, Name: "postgres",
				User: "postgres", Password: password, SSLMode: "require",
			}

			parsed, err := pgxpool.ParseConfig(cfg.DSN())
			if err != nil {
				t.Fatalf("pgx rejected the DSN: %v\nDSN: %s", err, cfg.DSN())
			}
			if got := parsed.ConnConfig.Password; got != password {
				t.Fatalf("password round-trip: got %q, want %q", got, password)
			}
			// The nastiest case: a password that reads as another field must
			// not actually set that field. Silently downgrading TLS because
			// the password contained "sslmode=disable" would be a security
			// failure, not a parsing curiosity.
			if parsed.ConnConfig.TLSConfig == nil {
				t.Fatal("sslmode was overridden by the password contents")
			}
		})
	}
}

// Empty Schema and Options must leave the DSN exactly as it was before this
// change, so a database-per-service deployment is unaffected.
func TestDSN_OmitsEmptyOptionalFields(t *testing.T) {
	cfg := DBConfig{
		Host: "postgres", Port: 5432, Name: "identity_context",
		User: "zoiko_app", Password: "pw", SSLMode: "disable",
	}
	dsn := cfg.DSN()

	if strings.Contains(dsn, "search_path") {
		t.Errorf("an unset schema must not emit search_path: %s", dsn)
	}
	if strings.HasSuffix(dsn, " ") {
		t.Errorf("unset options must not leave a trailing separator: %q", dsn)
	}

	parsed, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		t.Fatalf("pgx rejected the DSN: %v", err)
	}
	if _, set := parsed.ConnConfig.RuntimeParams["search_path"]; set {
		t.Error("search_path must be absent, not empty")
	}
	if parsed.ConnConfig.Database != "identity_context" {
		t.Errorf("dbname: got %q", parsed.ConnConfig.Database)
	}
}
