-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE payroll_runs NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pay_slips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE shadow_payroll_comparisons NO FORCE ROW LEVEL SECURITY;
ALTER TABLE pay_slip_items NO FORCE ROW LEVEL SECURITY;