package session

import (
	"context"
	"fmt"
	"time"

	"go.uber.org/zap"

	"zoiko.io/identity-context-svc/internal/domain"
	"zoiko.io/identity-context-svc/internal/events"
	"zoiko.io/identity-context-svc/internal/outbox"
)

// ContextStore is the durable half of session storage — Postgres
// session_contexts, added in migration 000005.
//
// Narrow on purpose. DurableCache needs to append evidence and to find what a
// principal still holds; it has no reason to reach anything else in the store.
type ContextStore interface {
	InsertSessionContext(ctx context.Context, sc domain.SessionContext) error

	// InsertSessionContextWithEvent writes the row and its outbox event
	// atomically. See package outbox for why that pairing matters.
	InsertSessionContextWithEvent(ctx context.Context, sc domain.SessionContext, rec outbox.Record) error

	MarkSessionInvalidated(ctx context.Context, sessionContextID, tenantID string, reason domain.InvalidationReason, at time.Time) error
	FindSessionContext(ctx context.Context, sessionContextID, tenantID string) (*domain.SessionContext, error)
	FindLiveSessionIDsForPrincipal(ctx context.Context, principalID, tenantID string, now time.Time) ([]string, error)
	FindLiveSessionIDsForTenant(ctx context.Context, tenantID string, now time.Time) ([]string, error)
}

// DurableCache is the SessionCache the resolver actually uses. It composes the
// Redis Cache with the Postgres ContextStore and adds the tenant scoping that
// neither layer can enforce on its own.
//
// Two things live here rather than in Cache:
//
//  1. TENANCY. Redis keys are flat: session:jwt:<ulid> says nothing about who
//     owns it. Every method taking a session id therefore also takes the
//     caller's verified tenant and refuses a record belonging to anyone else.
//     Before this existed, GET /v1/context/session/{id} returned any tenant's
//     signed envelope to any caller holding the id, and the invalidate route
//     would revoke any tenant's session — while every /v1/principals route
//     beside them scoped correctly on X-Tenant-Id.
//
//  2. DURABILITY. Redis holds sessions for the session window; Postgres holds
//     the evidence for the retention window. Reads prefer Redis and fall back;
//     writes go to both.
//
// The Postgres write is logged-and-swallowed, never fatal. A resolution that
// succeeded on all six dimensions must not be failed by an evidence-store
// hiccup — but the log line is ERROR, because a resolution nobody recorded is
// exactly what an outbox is meant to stop losing.
// HotCache is the Redis half of session storage, as DurableCache sees it.
//
// An interface rather than *Cache so the TENANCY LOGIC IN THIS FILE is testable
// without a Redis. That matters more than it sounds: everything DurableCache
// adds over its two halves is a security boundary — every method taking a
// session id also takes the caller's verified tenant and refuses a record
// belonging to anyone else — and before this it could only be exercised against
// live infrastructure, so in practice it was not exercised at all.
//
// *Cache satisfies it; the compile-time assertion is at the bottom of this file.
type HotCache interface {
	Put(ctx context.Context, sessionContextID, envelopeJWT string) error
	Get(ctx context.Context, sessionContextID string) (string, error)
	Evict(ctx context.Context, sessionContextID string) error
	PersistSessionContext(ctx context.Context, sc domain.SessionContext) error
	GetSessionContext(ctx context.Context, sessionContextID string) (*domain.SessionContext, error)
	Invalidate(ctx context.Context, sessionContextID string, reason domain.InvalidationReason, at time.Time) error
	SessionIDsForPrincipal(ctx context.Context, principalID string) ([]string, error)
	ClearPrincipalIndex(ctx context.Context, principalID string) error
	SessionIDsForEntity(ctx context.Context, legalEntityID string) ([]string, error)
	ClearEntityIndex(ctx context.Context, legalEntityID string) error
}

type DurableCache struct {
	cache HotCache
	store ContextStore
	log   *zap.Logger
}

// NewDurableCache wraps a Redis cache with a durable evidence store.
func NewDurableCache(cache HotCache, store ContextStore, log *zap.Logger) *DurableCache {
	return &DurableCache{cache: cache, store: store, log: log}
}

// *Cache is the production HotCache. Asserted at compile time so a signature
// change on either side is a build failure rather than a wiring surprise.
var _ HotCache = (*Cache)(nil)

// Put stores the signed envelope JWT. Tenancy is enforced on read, not here:
// the id is generated by the resolver in the same call that persisted the
// context record, so there is nothing yet to compare against.
func (d *DurableCache) Put(ctx context.Context, sessionContextID, envelopeJWT string) error {
	return d.cache.Put(ctx, sessionContextID, envelopeJWT)
}

// Get returns the signed envelope JWT for a session the caller's tenant owns.
//
// A session belonging to another tenant is reported as not-found rather than
// forbidden: "wrong tenant" confirms the id exists, which is the one bit a
// caller guessing ids should not get back.
func (d *DurableCache) Get(ctx context.Context, sessionContextID, tenantID string) (string, error) {
	sc, err := d.GetSessionContext(ctx, sessionContextID, tenantID)
	if err != nil {
		return "", err
	}
	if sc == nil {
		return "", fmt.Errorf("%w: %s", domain.ErrSessionNotFound, sessionContextID)
	}

	jwt, err := d.cache.Get(ctx, sessionContextID)
	if err != nil {
		// The context record outlives the envelope: Postgres holds it for the
		// retention window, Redis holds the JWT for the session window. A
		// record with no JWT is an expired session, not a store failure.
		return "", fmt.Errorf("%w: %s", domain.ErrSessionNotFound, sessionContextID)
	}
	return jwt, nil
}

// Evict removes the envelope JWT from cache.
func (d *DurableCache) Evict(ctx context.Context, sessionContextID string) error {
	return d.cache.Evict(ctx, sessionContextID)
}

// PersistSessionContext writes the hot cache entry and the durable record.
//
// Redis first: it is what the next request reads, and it is the write that can
// be retried harmlessly. A Postgres failure is logged and swallowed so the
// resolution still completes.
func (d *DurableCache) PersistSessionContext(ctx context.Context, sc domain.SessionContext) error {
	if err := d.cache.PersistSessionContext(ctx, sc); err != nil {
		return err
	}
	if err := d.store.InsertSessionContext(ctx, sc); err != nil {
		d.log.Error("session evidence not durably recorded",
			zap.String("session_context_id", sc.SessionContextID),
			zap.String("principal_id", sc.PrincipalID),
			zap.String("correlation_id", sc.CorrelationID),
			zap.Error(err),
		)
	}
	return nil
}

// PersistSessionContextWithEvent writes the durable evidence row and its
// identity.context.resolved event in one transaction, then warms the cache.
//
// ORDER IS THE POINT. Postgres first and fatally: if the row and the event do
// not both land, the caller must not issue an envelope, because no evidence of
// the issuance would exist anywhere. Redis second and best-effort: the
// envelope is self-contained and independently verifiable from the JWKS, so a
// missing cache entry costs a re-resolve rather than a lost session.
//
// This is the inverse of PersistSessionContext's order, which wrote Redis
// first and swallowed a Postgres failure. That was right when Postgres held
// only a duplicate of the cache; it is wrong now that Postgres holds the only
// copy of the event.
func (d *DurableCache) PersistSessionContextWithEvent(
	ctx context.Context,
	sc domain.SessionContext,
	ev domain.ContextResolvedEvent,
) error {
	rec, err := events.Render(
		events.EventContextResolved,
		ev.TenantID, ev.LegalEntityID, ev.PrincipalID, ev.CorrelationID, ev.SessionContextID,
		map[string]any{
			"principal_id":       ev.PrincipalID,
			"tenant_id":          ev.TenantID,
			"legal_entity_id":    ev.LegalEntityID,
			"session_context_id": ev.SessionContextID,
			"evidence_id":        ev.EvidenceID,
			"correlation_id":     ev.CorrelationID,
		})
	if err != nil {
		return fmt.Errorf("render context.resolved event: %w", err)
	}

	if err := d.store.InsertSessionContextWithEvent(ctx, sc, rec); err != nil {
		return fmt.Errorf("persist session evidence: %w", err)
	}

	if err := d.cache.PersistSessionContext(ctx, sc); err != nil {
		d.log.Warn("session context not cached — durable record is written, next read falls back to Postgres",
			zap.String("session_context_id", sc.SessionContextID),
			zap.Error(err))
	}
	return nil
}

// EvictAllForTenant revokes every live session in a tenant.
//
// Backs InvalidateTenantContext. Unlike the per-principal case there is no
// Redis reverse index by tenant, so the id set comes from the durable store
// alone — which is complete for this purpose, because the durable write is now
// the one that cannot be skipped.
func (d *DurableCache) EvictAllForTenant(
	ctx context.Context,
	tenantID string,
	reason domain.InvalidationReason,
) (int, error) {
	now := time.Now().UTC()
	ids, err := d.store.FindLiveSessionIDsForTenant(ctx, tenantID, now)
	if err != nil {
		return 0, fmt.Errorf("find live sessions for tenant: %w", err)
	}

	revoked := 0
	var firstErr error
	for _, id := range ids {
		if err := d.Invalidate(ctx, id, tenantID, reason, now); err != nil {
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		if err := d.cache.Evict(ctx, id); err != nil && firstErr == nil {
			firstErr = err
		}
		revoked++
	}
	return revoked, firstErr
}

// GetSessionContext reads the session record, preferring the cache.
//
// The Postgres fallback is what makes invalidation honest after the cache TTL.
// The resolver treats a missing record as an idempotent no-op, so before the
// fallback existed, revoking a session that had merely aged out of Redis
// reported success and wrote nothing anywhere.
func (d *DurableCache) GetSessionContext(ctx context.Context, sessionContextID, tenantID string) (*domain.SessionContext, error) {
	sc, err := d.cache.GetSessionContext(ctx, sessionContextID)
	if err != nil {
		d.log.Warn("session cache read failed — falling back to durable store",
			zap.String("session_context_id", sessionContextID),
			zap.Error(err),
		)
	}
	if sc == nil {
		sc, err = d.store.FindSessionContext(ctx, sessionContextID, tenantID)
		if err != nil {
			return nil, err
		}
	}
	if sc == nil {
		return nil, nil
	}
	if sc.TenantID != tenantID {
		// Not this caller's session — indistinguishable from absent.
		return nil, nil
	}
	return sc, nil
}

// Invalidate appends the invalidation to both stores. Idempotent: an
// already-invalidated session is a no-op in each.
func (d *DurableCache) Invalidate(
	ctx context.Context,
	sessionContextID, tenantID string,
	reason domain.InvalidationReason,
	at time.Time,
) error {
	sc, err := d.GetSessionContext(ctx, sessionContextID, tenantID)
	if err != nil {
		return err
	}
	if sc == nil {
		return nil
	}

	if err := d.cache.Invalidate(ctx, sessionContextID, reason, at); err != nil {
		return fmt.Errorf("invalidate cached session: %w", err)
	}
	if err := d.store.MarkSessionInvalidated(ctx, sessionContextID, tenantID, reason, at); err != nil {
		return fmt.Errorf("record session invalidation: %w", err)
	}
	return nil
}

// EvictAllForPrincipal revokes every live session a principal holds within the
// caller's tenant, and reports how many.
//
// The id set is the UNION of the Redis reverse index and the durable store's
// live rows. Neither alone is sufficient: Redis loses sessions on a flush or an
// eviction under memory pressure, and Postgres is the slower of the two to
// reflect a session issued moments ago. A revocation that missed sessions
// because one source was stale is the failure mode that matters here, so both
// are consulted and the union is revoked.
func (d *DurableCache) EvictAllForPrincipal(
	ctx context.Context,
	principalID, tenantID string,
	reason domain.InvalidationReason,
) (int, error) {
	now := time.Now().UTC()
	ids := make(map[string]struct{})

	cached, err := d.cache.SessionIDsForPrincipal(ctx, principalID)
	if err != nil {
		d.log.Warn("session index read failed — relying on durable store alone",
			zap.String("principal_id", principalID),
			zap.Error(err),
		)
	}
	for _, id := range cached {
		ids[id] = struct{}{}
	}

	durable, err := d.store.FindLiveSessionIDsForPrincipal(ctx, principalID, tenantID, now)
	if err != nil {
		// Fail outright only if the cache gave us nothing either — a partial
		// revocation beats none.
		if len(ids) == 0 {
			return 0, fmt.Errorf("find live sessions: %w", err)
		}
		d.log.Warn("durable session lookup failed — revoking cached set only",
			zap.String("principal_id", principalID),
			zap.Error(err),
		)
	}
	for _, id := range durable {
		ids[id] = struct{}{}
	}

	revoked := 0
	var firstErr error
	for id := range ids {
		// Invalidate re-checks tenancy per session, so an id that reached the
		// Redis index from another tenant is skipped rather than revoked.
		if err := d.Invalidate(ctx, id, tenantID, reason, now); err != nil {
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		if err := d.cache.Evict(ctx, id); err != nil && firstErr == nil {
			firstErr = err
		}
		revoked++
	}

	if err := d.cache.ClearPrincipalIndex(ctx, principalID); err != nil && firstErr == nil {
		firstErr = err
	}
	return revoked, firstErr
}

// EvictAllForEntity revokes every live session scoped to a legal entity.
//
// entity.updated changes what a legal entity IS — its jurisdiction, its
// lifecycle state, its residency policy. Envelopes already issued against it
// carry the old shape, so they are revoked and the next resolve re-derives
// them. Unlike the principal case there is no durable counterpart index: an
// entity's live sessions are found through Redis only, and the log line says
// so rather than implying completeness it cannot offer.
func (d *DurableCache) EvictAllForEntity(
	ctx context.Context,
	legalEntityID, tenantID string,
	reason domain.InvalidationReason,
) (int, error) {
	ids, err := d.cache.SessionIDsForEntity(ctx, legalEntityID)
	if err != nil {
		return 0, err
	}
	if len(ids) == 0 {
		return 0, nil
	}

	now := time.Now().UTC()
	revoked := 0
	var firstErr error
	for _, id := range ids {
		if err := d.Invalidate(ctx, id, tenantID, reason, now); err != nil {
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		if err := d.cache.Evict(ctx, id); err != nil && firstErr == nil {
			firstErr = err
		}
		revoked++
	}

	if err := d.cache.ClearEntityIndex(ctx, legalEntityID); err != nil && firstErr == nil {
		firstErr = err
	}
	return revoked, firstErr
}
