-- currency-registry-svc (REF-02) -- global reference schema.
--
-- WHY THESE TABLES HAVE NO tenant_id AND NO ROW-LEVEL SECURITY
--
-- A currency is not tenant data. ISO 4217 membership, numeric codes and
-- minor-unit exponents are the same for every tenant, and they must be readable
-- BEFORE a tenant context exists (e.g. while a tenant is being provisioned), the
-- same posture tenant-entity-registry-svc takes for residency_regions. A
-- tenant_id column here would be a lie ("whose currency is USD?") and RLS would
-- either hide the platform's own reference data or need a bypass that is a
-- larger hole than the absence of the policy.
--
-- What IS tenant-specific -- which currencies a tenant has enabled -- lives in
-- tenant_currency_support (migration 000003), with tenant_id and FORCE RLS.
-- Isolation of the global tables rests on: (1) writes only through the named
-- commands, each authorised by authorization-svc; (2) append-only/no-delete
-- triggers (migration 000002); (3) the runtime role holding DML only.
--
-- No hard delete anywhere: retirement is a status transition plus valid_to.

CREATE TABLE IF NOT EXISTS currencies (
    currency_id         UUID PRIMARY KEY,                      -- UUIDv7, generated by the service
    alpha_code          CHAR(3) NOT NULL,                      -- ISO 4217 alpha: an ATTRIBUTE, not identity
    numeric_code        CHAR(3) NOT NULL,                      -- ISO 4217 numeric
    name                TEXT NOT NULL,
    fund_or_metal_flag  BOOLEAN NOT NULL DEFAULT false,
    status              TEXT NOT NULL,
    valid_from          TIMESTAMPTZ NOT NULL,
    valid_to            TIMESTAMPTZ,
    version             BIGINT NOT NULL DEFAULT 1,
    -- SoD evidence: the import that last introduced/changed this row and who applied it.
    last_import_id      UUID,
    last_import_actor   TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT currencies_status_known CHECK (status IN ('KNOWN', 'SUPPORTED', 'RESTRICTED', 'RETIRED')),
    CONSTRAINT currencies_alpha_shape CHECK (alpha_code ~ '^[A-Z]{3}$'),
    CONSTRAINT currencies_numeric_shape CHECK (numeric_code ~ '^[0-9]{3}$'),
    CONSTRAINT currencies_name_nonempty CHECK (length(name) BETWEEN 1 AND 200),
    CONSTRAINT currencies_valid_window CHECK (valid_to IS NULL OR valid_to >= valid_from),
    -- Retirement is a status AND an end date, never one without the other.
    CONSTRAINT currencies_retired_has_valid_to CHECK ((status = 'RETIRED') = (valid_to IS NOT NULL)),
    CONSTRAINT currencies_version_positive CHECK (version >= 1)
);

-- Unique codes among NON-retired currencies; retired rows keep their codes
-- ("historical codes retained") without blocking.
CREATE UNIQUE INDEX IF NOT EXISTS ux_currencies_alpha_active   ON currencies (alpha_code)   WHERE status <> 'RETIRED';
CREATE UNIQUE INDEX IF NOT EXISTS ux_currencies_numeric_active ON currencies (numeric_code) WHERE status <> 'RETIRED';
CREATE INDEX IF NOT EXISTS idx_currencies_alpha   ON currencies (alpha_code);
CREATE INDEX IF NOT EXISTS idx_currencies_numeric ON currencies (numeric_code);
CREATE INDEX IF NOT EXISTS idx_currencies_status  ON currencies (status, alpha_code);

-- Source-import evidence: manifest, hash, verdict, quarantine reasons.
-- (source_name, source_version, manifest_hash) is the import idempotency key.
CREATE TABLE IF NOT EXISTS currency_imports (
    import_id          UUID PRIMARY KEY,
    source_name        TEXT NOT NULL,
    source_version     TEXT NOT NULL,
    manifest_hash      TEXT NOT NULL,
    status             TEXT NOT NULL,
    row_count          INTEGER NOT NULL,
    quarantine_reason  TEXT,
    rows               JSONB NOT NULL,          -- the submitted payload, retained as evidence
    row_errors         JSONB,
    summary            JSONB,
    effective_at       TIMESTAMPTZ NOT NULL,
    actor              TEXT NOT NULL,
    actor_tenant_id    TEXT NOT NULL,
    reason             TEXT NOT NULL,
    correlation_id     TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT currency_imports_status_known CHECK (status IN ('RECEIVED', 'VALIDATED', 'APPLIED', 'QUARANTINED')),
    CONSTRAINT currency_imports_quarantine_has_reason CHECK ((status = 'QUARANTINED') = (quarantine_reason IS NOT NULL)),
    CONSTRAINT currency_imports_idempotency UNIQUE (source_name, source_version, manifest_hash)
);
CREATE INDEX IF NOT EXISTS idx_currency_imports_source ON currency_imports (source_name, source_version);

ALTER TABLE currencies
    ADD CONSTRAINT currencies_last_import_fk FOREIGN KEY (last_import_id) REFERENCES currency_imports (import_id);

-- Minor-unit metadata is versioned and APPEND-ONLY. A change inserts a new row;
-- the previous row is never updated (trigger in 000002). The end of a version's
-- validity is DERIVED (next row's valid_from, or the currency's valid_to) so no
-- UPDATE is ever needed to "close" it.
CREATE TABLE IF NOT EXISTS currency_minor_unit_versions (
    currency_id     UUID NOT NULL REFERENCES currencies (currency_id),
    minor_unit      SMALLINT NOT NULL,
    valid_from      TIMESTAMPTZ NOT NULL,
    source_version  TEXT NOT NULL,
    import_id       UUID REFERENCES currency_imports (import_id),
    evidence_ref    TEXT NOT NULL,
    recorded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (currency_id, valid_from),
    CONSTRAINT currency_minor_unit_range CHECK (minor_unit BETWEEN 0 AND 6)
);

-- Append-only lifecycle history: who moved what, why, approved by whom.
CREATE TABLE IF NOT EXISTS currency_status_history (
    history_id          UUID PRIMARY KEY,
    currency_id         UUID NOT NULL REFERENCES currencies (currency_id),
    from_status         TEXT NOT NULL,
    to_status           TEXT NOT NULL,
    actor               TEXT NOT NULL,
    approver            TEXT,
    reason              TEXT NOT NULL,
    effective_at        TIMESTAMPTZ NOT NULL,
    recorded_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    resulting_version   BIGINT NOT NULL,
    correlation_id      TEXT,
    CONSTRAINT currency_status_history_known CHECK (
        from_status IN ('KNOWN', 'SUPPORTED', 'RESTRICTED', 'RETIRED')
        AND to_status IN ('KNOWN', 'SUPPORTED', 'RESTRICTED', 'RETIRED')),
    CONSTRAINT currency_status_history_moves CHECK (from_status <> to_status)
);
CREATE INDEX IF NOT EXISTS idx_currency_status_history_currency ON currency_status_history (currency_id, recorded_at);
