// Package storage defines the boundary between this service and wherever
// document bytes actually live.
//
// LocalFileBackend is the v1 implementation: real AES-256-GCM encryption at
// rest against local files, one per stored blob — the same "real local
// encryption now, real object storage later" posture as secret-vault-
// integration-svc's LocalFileVaultBackend, adapted for documents (which can
// be far larger than secrets, so each blob gets its own file rather than one
// shared JSON store). Swapping to Vasu's S3-compatible object storage model
// later means implementing Backend against that client — nothing above this
// package changes.
package storage

import (
	"context"
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// ErrObjectNotFound is returned by Get when no blob has ever been Put for key.
var ErrObjectNotFound = errors.New("storage: object not found")

// ErrIntegrityFailure is returned by Get when the decrypted content's SHA-256
// does not match the checksum recorded at write time — real tamper detection,
// not a no-op (§8.3 "integrity validation / checksum controls").
var ErrIntegrityFailure = errors.New("storage: integrity check failed — content does not match recorded checksum")

// Backend is the narrow interface the store layer depends on.
type Backend interface {
	// Put encrypts data at rest under key and returns its SHA-256 checksum
	// (hex-encoded), computed over the PLAINTEXT before encryption.
	Put(ctx context.Context, key string, data []byte) (checksumSHA256 string, err error)

	// Get decrypts the blob at key and verifies it against wantChecksum
	// (the checksum recorded in document_versions at write time). Returns
	// ErrIntegrityFailure if they don't match — this is the read-time half
	// of tamper detection, not just a write-time formality.
	Get(ctx context.Context, key string, wantChecksumSHA256 string) ([]byte, error)
}

// LocalFileBackend implements Backend against a directory of encrypted
// files, one per key, each AES-256-GCM encrypted. Not safe for concurrent
// writes to the SAME key (no file locking) — acceptable for v1: document
// versions are immutable once written, so no key is ever overwritten.
type LocalFileBackend struct {
	dir string
	gcm cipher.AEAD
}

// NewLocalFileBackend constructs a LocalFileBackend rooted at dir.
// masterKeyHex must decode to exactly 32 bytes (AES-256) — fails fast on a
// missing or wrong-length key rather than silently running unencrypted.
func NewLocalFileBackend(dir, masterKeyHex string) (*LocalFileBackend, error) {
	if masterKeyHex == "" {
		return nil, errors.New("storage: DOCUMENT_VAULT_MASTER_KEY_HEX must be set (32-byte AES-256 key, hex-encoded)")
	}
	key, err := hex.DecodeString(masterKeyHex)
	if err != nil {
		return nil, fmt.Errorf("storage: DOCUMENT_VAULT_MASTER_KEY_HEX is not valid hex: %w", err)
	}
	if len(key) != 32 {
		return nil, fmt.Errorf("storage: DOCUMENT_VAULT_MASTER_KEY_HEX must decode to 32 bytes (AES-256), got %d", len(key))
	}
	block, err := aes.NewCipher(key)
	if err != nil {
		return nil, fmt.Errorf("storage: failed to construct AES cipher: %w", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		return nil, fmt.Errorf("storage: failed to construct GCM mode: %w", err)
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("storage: failed to create root dir: %w", err)
	}
	return &LocalFileBackend{dir: dir, gcm: gcm}, nil
}

// path maps a logical key to an on-disk path. Keys are generated by the
// store layer (document ID + version), never user-supplied directly, so this
// does not need to defend against path traversal from external input — but
// it still normalizes via filepath.Base as a second line of defence.
func (b *LocalFileBackend) path(key string) string {
	return filepath.Join(b.dir, filepath.Base(key)+".enc")
}

func (b *LocalFileBackend) Put(_ context.Context, key string, data []byte) (string, error) {
	checksum := sha256.Sum256(data)
	checksumHex := hex.EncodeToString(checksum[:])

	nonce := make([]byte, b.gcm.NonceSize())
	if _, err := rand.Read(nonce); err != nil {
		return "", fmt.Errorf("storage: failed to generate nonce: %w", err)
	}
	ciphertext := b.gcm.Seal(nonce, nonce, data, nil) // nonce prefixed to ciphertext

	if err := os.WriteFile(b.path(key), ciphertext, 0o600); err != nil {
		return "", fmt.Errorf("storage: failed to write object: %w", err)
	}
	return checksumHex, nil
}

func (b *LocalFileBackend) Get(_ context.Context, key string, wantChecksumSHA256 string) ([]byte, error) {
	raw, err := os.ReadFile(b.path(key))
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrObjectNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("storage: failed to read object: %w", err)
	}

	nonceSize := b.gcm.NonceSize()
	if len(raw) < nonceSize {
		return nil, fmt.Errorf("storage: object %q is corrupt (too short)", key)
	}
	nonce, ciphertext := raw[:nonceSize], raw[nonceSize:]
	plaintext, err := b.gcm.Open(nil, nonce, ciphertext, nil)
	if err != nil {
		return nil, fmt.Errorf("storage: decryption failed for %q (wrong key or corrupt data): %w", key, err)
	}

	got := sha256.Sum256(plaintext)
	if hex.EncodeToString(got[:]) != wantChecksumSHA256 {
		return nil, ErrIntegrityFailure
	}
	return plaintext, nil
}

var _ Backend = (*LocalFileBackend)(nil)
