// Code generated by services/_contract/rollout.sh. DO NOT EDIT.
//
// Regenerate with: services/_contract/rollout.sh spend-controls-svc

package envelope

// ServicePolicy is this service's §4 conditional-field policy.
//
// The unconditionally mandatory fields — tenant_id, actor_subject_id,
// request_id, correlation_id, source_channel — and idempotency_key on material
// writes are enforced for every service and are not expressible here.
func ServicePolicy() Policy {
	return Policy{
		ServiceName: "spend-controls-svc",

		// §4: mandatory for entity-specific records (INV-02).
		LegalEntityID: RequiredOnWrite,

		// §4: required for governed sensitive access.
		PurposeContext: NotRequired,

		// This service does not post to an accounting book.
		BookID: NotRequired,
	}
}
