-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE bank_accounts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cash_balances NO FORCE ROW LEVEL SECURITY;
ALTER TABLE liquidity_thresholds NO FORCE ROW LEVEL SECURITY;
ALTER TABLE transfers NO FORCE ROW LEVEL SECURITY;