// Code generated by services/_contract/rollout.sh. DO NOT EDIT.
//
// NOTE: written by hand for currency-registry-svc because rollout.sh's service
// list has not been extended for this new service (see SPEC_DEVIATIONS.md).
// The shape is identical to what rollout.sh generates for sibling services.

package envelope

// ServicePolicy is this service's §4 conditional-field policy.
//
// The unconditionally mandatory fields — tenant_id, actor_subject_id,
// request_id, correlation_id, source_channel — and idempotency_key on material
// writes are enforced for every service and are not expressible here.
func ServicePolicy() Policy {
	return Policy{
		ServiceName: "currency-registry-svc",

		// Currencies are global reference data; no legal entity scopes them.
		LegalEntityID: NotRequired,

		PurposeContext: NotRequired,

		// This service does not post to an accounting book.
		BookID: NotRequired,
	}
}
