// Code generated by tools/servicectl. DO NOT EDIT BY HAND.
//
// Derived from deployments/docker-compose*.yml (each service's environment and
// database name) and the console's lib/api/config.ts (the ports it expects).
//
// PORTS ARE UNIQUE HERE AND WERE NOT BEFORE. The four compose files were never
// meant to run together, so sixteen ports were claimed twice across them, and
// four were claimed twice inside the console's own registry. A launcher that can
// start any service at any moment turns each port into an allocation rather than
// a per-file convention. Services the main compose file runs today keep the port
// they already had; the rest moved into 8200+.
//
// CROSS-SERVICE URLS ARE RESOLVED FROM THE VARIABLE NAME, not from the value
// compose carried. Fourteen values named a different service than their own key:
// six services asked authorization-svc for jurisdiction rules, six pointed
// AUTHZ_SERVICE_URL at host.docker.internal:8081 (the tenant registry's port),
// filing-preparation-svc asked it for evidence manifests, and corporate-tax-svc
// addressed general-ledger-svc on :8091 instead of :8098. Under Docker most of
// these never fired, because the services carrying them were in compose files
// that were never started alongside the main one.

package main

// generatedServices is the authoritative service table: 86 services.
var generatedServices = []Service{
	{
		Name:   "access-control-svc",
		Port:   8137,
		DBName: "access_control",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.access-control.events",
		},
	},
	{
		Name:   "accounts-payable-svc",
		Port:   8099,
		DBName: "accounts_payable",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.accounts-payable.events",
		},
	},
	{
		Name:   "accounts-receivable-svc",
		Port:   8101,
		DBName: "accounts_receivable",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":  "zoiko.accounts-receivable.events",
			"LEDGER_SERVICE_URL":  "http://127.0.0.1:8098",
			"TENANT_REGISTRY_URL": "http://127.0.0.1:8081",
		},
	},
	{
		Name:   "ai-governance-svc",
		Port:   8146,
		DBName: "ai_governance",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.ai-governance.events",
		},
	},
	{
		Name:   "anomaly-detection-svc",
		Port:   8200,
		DBName: "anomaly_detection",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.anomaly-detection.events",
		},
	},
	{
		Name:   "audit-event-store-svc",
		Port:   8084,
		DBName: "audit_event_store",
		Env: map[string]string{
			"KAFKA_GROUP_ID": "audit-event-store-svc",
			"KAFKA_TOPICS":   "zoiko.identity.events,zoiko.entity.events",
		},
	},
	{
		Name:   "authorization-svc",
		Port:   8089,
		DBName: "authorization_svc",
		Env: map[string]string{
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.authorization.events",
			"KAFKA_GROUP_ID":         "authorization-svc",
			"SIEM_SERVICE_URL":       "http://127.0.0.1:8214",
		},
	},
	{
		Name:   "bank-reconciliation-svc",
		Port:   8102,
		DBName: "bank_reconciliation",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.bank-reconciliation.events",
			"LEDGER_SERVICE_URL": "http://127.0.0.1:8098",
		},
	},
	{
		Name:   "banking-connector-svc",
		Port:   8201,
		DBName: "zoiko_banking_connector",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.banking.connector.events",
		},
	},
	{
		Name:   "benefits-svc",
		Port:   8112,
		DBName: "benefits",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.benefits.events",
		},
	},
	{
		Name:   "board-resolutions-svc",
		Port:   8122,
		DBName: "board_resolutions",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"EVIDENCE_REQ_URL":       "http://127.0.0.1:8130",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.board-resolutions.events",
		},
	},
	{
		Name:   "capability-registry-svc",
		Port:   8145,
		DBName: "capability_registry",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.capability-registry.events",
		},
	},
	{
		Name:   "carta-svc",
		Port:   8142,
		DBName: "",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
		},
	},
	{
		Name:   "clause-template-svc",
		Port:   8120,
		DBName: "clause_template",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.clause.events",
		},
	},
	{
		Name:   "commercial-account-svc",
		Port:   8144,
		DBName: "commercial_account",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.commercial-account.events",
		},
	},
	{
		Name:   "compensation-svc",
		Port:   8111,
		DBName: "compensation",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.compensation.events",
		},
	},
	{
		Name:   "compliance-risk-scoring-svc",
		Port:   8202,
		DBName: "compliance_risk_scoring",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.compliance-risk-scoring.events",
		},
	},
	{
		Name:   "compliance-status-svc",
		Port:   8132,
		DBName: "compliance_status",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.compliance-status.events",
		},
	},
	{
		Name:   "configuration-feature-flag-svc",
		Port:   8086,
		DBName: "configuration_feature_flag",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID": "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":      "zoiko.configuration.events",
			"KAFKA_GROUP_ID":          "configuration-feature-flag-svc",
		},
	},
	{
		Name:   "connectivity-api-bridge-svc",
		Port:   8203,
		DBName: "zoiko_connectivity_api_bridge",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.connectivity.api.bridge.events",
		},
	},
	{
		Name:   "consolidation-svc",
		Port:   8106,
		DBName: "consolidation_svc",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":        "http://127.0.0.1:8089",
			"INTERCOMPANY_SERVICE_URL": "http://127.0.0.1:8105",
			"KAFKA_EVENTS_TOPIC":       "zoiko.consolidation.events",
			"LEDGER_SERVICE_URL":       "http://127.0.0.1:8098",
		},
	},
	{
		Name:   "contract-lifecycle-svc",
		Port:   8119,
		DBName: "contract_lifecycle",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"GOVERNANCE_LOG_URL":     "http://127.0.0.1:8083",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.contract.events",
		},
	},
	{
		Name:   "corporate-actions-svc",
		Port:   8123,
		DBName: "corporate_actions",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"EVIDENCE_REQ_URL":       "http://127.0.0.1:8130",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.corporate-actions.events",
		},
	},
	{
		Name:   "corporate-tax-svc",
		Port:   8128,
		DBName: "corporate_tax",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"GENERAL_LEDGER_URL":     "http://127.0.0.1:8098",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.corporate-tax.events",
			"TAX_RULES_SERVICE_URL":  "http://127.0.0.1:8125",
		},
	},
	{
		Name:   "counterparty-management-svc",
		Port:   8124,
		DBName: "counterparty_management",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.counterparty.events",
		},
	},
	{
		Name:   "decision-support-svc",
		Port:   8138,
		DBName: "decision_support",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":           "http://127.0.0.1:8089",
			"GOVERNANCE_DECISION_LOG_URL": "http://127.0.0.1:8083",
			"KAFKA_EVENTS_TOPIC":          "zoiko.decision-support.events",
		},
	},
	{
		Name:   "delegated-authority-svc",
		Port:   8136,
		DBName: "delegated_authority",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.delegated-authority.events",
		},
	},
	{
		Name:   "document-vault-svc",
		Port:   8094,
		DBName: "document_vault",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":             "http://127.0.0.1:8089",
			"DOCUMENT_VAULT_MASTER_KEY_HEX": "0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f",
			"STORAGE_DIR":                   "/data/documents",
			"TENANT_REGISTRY_URL":           "http://127.0.0.1:8081",
		},
	},
	{
		Name:   "employee-master-svc",
		Port:   8108,
		DBName: "employee_master",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.employee.events",
		},
	},
	{
		Name:   "employment-contracts-svc",
		Port:   8109,
		DBName: "employment_contracts",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.contract.events",
		},
	},
	{
		Name:   "esignature-integration-svc",
		Port:   8204,
		DBName: "zoiko_esignature_integration",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.esignature.integration.events",
		},
	},
	{
		Name:   "evidence-manifest-svc",
		Port:   8095,
		DBName: "evidence_manifest",
		Env: map[string]string{
			"AUTHORIZATION_SERVICE_URL":           "http://127.0.0.1:8089",
			"GOVERNANCE_DECISION_LOG_SERVICE_URL": "http://127.0.0.1:8083",
			"KAFKA_EVENTS_TOPIC":                  "zoiko.evidence.events",
			"WORKFLOW_SERVICE_URL":                "http://127.0.0.1:8090",
		},
	},
	{
		Name:   "evidence-requirements-svc",
		Port:   8130,
		DBName: "evidence_requirements",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":          "http://127.0.0.1:8089",
			"DOCUMENT_VAULT_SERVICE_URL": "http://127.0.0.1:8094",
			"KAFKA_EVENTS_TOPIC":         "zoiko.evidence-requirements.events",
		},
	},
	{
		Name:   "exception-escalation-svc",
		Port:   8205,
		DBName: "exception_escalation",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.exception-escalation.events",
		},
	},
	{
		Name:   "external-data-feed-svc",
		Port:   8206,
		DBName: "zoiko_external_data_feed",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.external.data.feed.events",
		},
	},
	{
		Name:   "filing-preparation-svc",
		Port:   8207,
		DBName: "filing_preparation",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"EVIDENCE_MANIFEST_URL":  "http://127.0.0.1:8095",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.filing-prep.events",
		},
	},
	{
		Name:   "filing-tracker-svc",
		Port:   8141,
		DBName: "filing_tracker",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.filing-tracker.events",
		},
	},
	{
		Name:   "financial-close-svc",
		Port:   8104,
		DBName: "financial_close",
		Env: map[string]string{
			"AP_SERVICE_URL":     "http://127.0.0.1:8099",
			"AR_SERVICE_URL":     "http://127.0.0.1:8101",
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.close.events",
			"LEDGER_SERVICE_URL": "http://127.0.0.1:8098",
			"VAULT_SERVICE_URL":  "http://127.0.0.1:8094",
		},
	},
	{
		Name:   "forecasting-svc",
		Port:   8208,
		DBName: "forecasting",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.forecasting.events",
		},
	},
	{
		Name:   "gateway-auth-svc",
		Port:   8092,
		DBName: "",
		Env: map[string]string{
			"CARTA_SERVICE_URL":                  "http://127.0.0.1:8142",
			"EXPECTED_AUDIENCE":                  "zoiko-internal",
			"EXPECTED_ISSUER":                    "identity-context-svc",
			"IDENTITY_JWKS_URL":                  "http://127.0.0.1:8080/.well-known/jwks.json",
			"SIEM_SERVICE_URL":                   "http://127.0.0.1:8214",
			"TENANT_CONTEXT_STALE_GRACE_SECONDS": "120",
			"TENANT_CONTEXT_TTL_SECONDS":         "30",
			"TENANT_REGISTRY_URL":                "http://127.0.0.1:8081",
		},
	},
	{
		Name:   "general-ledger-svc",
		Port:   8098,
		DBName: "general_ledger",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.general-ledger.events",
		},
	},
	{
		Name:   "governance-decision-log-svc",
		Port:   8083,
		DBName: "governance_decision_log",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID": "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":      "zoiko.governance.events",
			"KAFKA_GROUP_ID":          "governance-decision-log-svc",
			"POLICY_SERVICE_URL":      "http://127.0.0.1:8085",
		},
	},
	{
		Name:   "hris-connector-svc",
		Port:   8209,
		DBName: "zoiko_hris_connector",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.hris.connector.events",
		},
	},
	{
		Name:   "identity-context-svc",
		Port:   8080,
		DBName: "identity_context",
		Env: map[string]string{
			"ACCESS_CONTROL_URL":           "http://127.0.0.1:8137",
			"AUTHZ_SERVICE_URL":            "http://127.0.0.1:8089",
			"ARGON2_ITERATIONS":            "2",
			"ARGON2_MAX_CONCURRENT":        "4",
			"ARGON2_MEMORY_KIB":            "19456",
			"ARGON2_PARALLELISM":           "1",
			"AUTH_LOCK_DURATION_SECONDS":   "900",
			"AUTH_MAX_FAILED_ATTEMPTS":     "5",
			"IDP_TOKEN_TTL_SECONDS":        "300",
			"JWT_SIGNING_PRIVATE_KEY_PATH": "/keys/envelope_signing_key.pem",
			"KAFKA_EVENTS_TOPIC":           "zoiko.identity.events",
			"KAFKA_GROUP_ID":               "identity-context-svc",
			"SIEM_SERVICE_URL":             "http://127.0.0.1:8214",
			"TENANT_REGISTRY_URL":          "http://127.0.0.1:8081",
		},
	},
	{
		Name:   "intercompany-accounting-svc",
		Port:   8105,
		DBName: "intercompany_accounting",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.intercompany.events",
			"LEDGER_SERVICE_URL": "http://127.0.0.1:8098",
		},
	},
	{
		Name:   "invoice-approval-svc",
		Port:   8107,
		DBName: "invoice_approval",
		Env: map[string]string{
			"AP_SERVICE_URL":       "http://127.0.0.1:8099",
			"AUTHZ_SERVICE_URL":    "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":   "zoiko.invoice-approval.events",
			"WORKFLOW_SERVICE_URL": "http://127.0.0.1:8090",
		},
	},
	{
		Name:   "jurisdiction-rules-svc",
		Port:   8082,
		DBName: "jurisdiction_rules",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID": "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":      "zoiko.jurisdiction.events",
			"KAFKA_GROUP_ID":          "jurisdiction-rules-svc",
		},
	},
	{
		Name:   "key-management-svc",
		Port:   8143,
		DBName: "",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"SIEM_SERVICE_URL":  "http://127.0.0.1:8214",
		},
	},
	{
		Name:   "kill-switch-registry-svc",
		Port:   8147,
		DBName: "kill_switch_registry",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.kill-switch-registry.events",
		},
	},
	{
		Name:   "leave-absence-svc",
		Port:   8115,
		DBName: "leave_absence",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.leaveabsence.events",
		},
	},
	{
		Name:   "metric-registry-svc",
		Port:   8149,
		DBName: "metric_registry",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.metric-registry.events",
		},
	},
	{
		Name:   "migration-integrity-svc",
		Port:   8210,
		DBName: "migration_integrity",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.migration-integrity.events",
		},
	},
	{
		Name:   "mtls-management-svc",
		Port:   8140,
		DBName: "",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"CA_DATA_DIR":       "/data/ca",
			"SIEM_SERVICE_URL":  "http://127.0.0.1:8214",
		},
	},
	{
		Name:   "notification-svc",
		Port:   8133,
		DBName: "notification",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.notification.events",
		},
	},
	{
		Name:   "obligation-tracking-svc",
		Port:   8121,
		DBName: "obligation_tracking",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.obligation-tracking.events",
		},
	},
	{
		Name:   "obligations-svc",
		Port:   8088,
		DBName: "obligations",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.obligations.events",
			"KAFKA_GROUP_ID":         "obligations-svc",
		},
	},
	{
		Name:   "offboarding-severance-svc",
		Port:   8117,
		DBName: "offboarding_severance",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL":    "http://127.0.0.1:8108",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.offboarding.events",
		},
	},
	{
		Name:   "org-structure-svc",
		Port:   8116,
		DBName: "org_structure",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.orgstructure.events",
		},
	},
	{
		Name:   "payroll-exceptions-svc",
		Port:   8114,
		DBName: "payroll_exceptions",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.payrollexceptions.events",
		},
	},
	{
		Name:   "payroll-run-svc",
		Port:   8110,
		DBName: "payroll_run",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":        "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL":      "http://127.0.0.1:8108",
			"EMPLOYMENT_CONTRACTS_URL": "http://127.0.0.1:8109",
			"KAFKA_EVENTS_TOPIC":       "zoiko.payroll.events",
		},
	},
	{
		Name:   "payroll-tax-svc",
		Port:   8113,
		DBName: "payroll_tax",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.payrolltax.events",
		},
	},
	{
		Name:   "performance-review-svc",
		Port:   8139,
		DBName: "performance_review",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":   "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL": "http://127.0.0.1:8108",
			"KAFKA_EVENTS_TOPIC":  "zoiko.performance-review.events",
		},
	},
	{
		Name:   "policy-svc",
		Port:   8085,
		DBName: "policy",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID":             "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":                   "http://127.0.0.1:8089",
			"GOVERNANCE_DECISION_LOG_SERVICE_URL": "http://127.0.0.1:8083",
			"KAFKA_EVENTS_TOPIC":                  "zoiko.policy.events",
			"KAFKA_GROUP_ID":                      "policy-svc",
		},
	},
	{
		Name:   "procurement-workflow-svc",
		Port:   8134,
		DBName: "procurement_workflow",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.procurement-workflow.events",
			"PURCHASE_ORDER_URL": "http://127.0.0.1:8129",
			"SPEND_CONTROLS_URL": "http://127.0.0.1:8131",
		},
	},
	{
		Name:   "purchase-order-svc",
		Port:   8129,
		DBName: "purchase_order",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":            "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":           "zoiko.purchase-order.events",
			"PURCHASE_REQUEST_SERVICE_URL": "http://127.0.0.1:8100",
		},
	},
	{
		Name:   "purchase-request-svc",
		Port:   8100,
		DBName: "purchase_request",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.purchase-request.events",
		},
	},
	{
		Name:   "reconciliation-intelligence-svc",
		Port:   8211,
		DBName: "reconciliation_intelligence",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.reconciliation-intelligence.events",
		},
	},
	{
		Name:   "reporting-orchestration-svc",
		Port:   8212,
		DBName: "reporting_orchestration",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_TOPIC":       "zoiko.reporting-orchestration.events",
		},
	},
	{
		Name:   "retention-registry-svc",
		Port:   8148,
		DBName: "retention_registry",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.retention-registry.events",
		},
	},
	{
		Name:   "schema-registry-svc",
		Port:   8093,
		DBName: "schema_registry",
		Env: map[string]string{
			"AUTHORIZATION_SERVICE_URL": "http://127.0.0.1:8089",
			"AUTHZ_PLATFORM_SCOPE_ID":   "00000000-0000-0000-0000-00000000f001",
		},
	},
	{
		Name:   "search-indexer-svc",
		Port:   8213,
		DBName: "",
	},
	{
		Name:   "secret-vault-integration-svc",
		Port:   8087,
		DBName: "secret_vault_integration",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID": "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":      "zoiko.secretvault.events",
			"KAFKA_GROUP_ID":          "secret-vault-integration-svc",
			"VAULT_LOCAL_STORE_PATH":  "/tmp/secret_store.local",
			"VAULT_MASTER_KEY_HEX":    "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
		},
	},
	{
		Name:   "siem-integration-svc",
		Port:   8214,
		DBName: "",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL": "http://127.0.0.1:8089",
		},
	},
	{
		Name:   "source-authority-svc",
		Port:   8150,
		DBName: "source_authority",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.source-authority.events",
		},
	},
	{
		Name:   "spend-controls-svc",
		Port:   8131,
		DBName: "spend_controls",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.spend-controls.events",
		},
	},
	{
		Name:   "tax-authority-interface-svc",
		Port:   8215,
		DBName: "zoiko_tax_authority_interface",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":  "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC": "zoiko.tax.authority.interface.events",
		},
	},
	{
		Name:   "tax-determination-svc",
		Port:   8126,
		DBName: "tax_determination",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.tax-determination.events",
			"TAX_RULES_SERVICE_URL":  "http://127.0.0.1:8125",
		},
	},
	{
		Name:   "tax-rules-svc",
		Port:   8125,
		DBName: "tax_rules",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.tax-rules.events",
		},
	},
	{
		Name:   "tenant-entity-registry-svc",
		Port:   8081,
		DBName: "tenant_entity_registry",
		Env: map[string]string{
			"AUTHZ_PLATFORM_SCOPE_ID": "00000000-0000-0000-0000-00000000f001",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL":  "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":      "zoiko.entity.events",
			"KAFKA_GROUP_ID":          "tenant-entity-registry-svc",
		},
	},
	{
		Name:   "treasury-svc",
		Port:   8103,
		DBName: "treasury",
		Env: map[string]string{
			"AP_SERVICE_URL":          "http://127.0.0.1:8099",
			"AR_SERVICE_URL":          "http://127.0.0.1:8101",
			"AUTHZ_SERVICE_URL":       "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":      "zoiko.treasury.events",
			"LEDGER_SERVICE_URL":      "http://127.0.0.1:8098",
			"OBLIGATIONS_SERVICE_URL": "http://127.0.0.1:8088",
		},
	},
	{
		Name:   "vat-gst-svc",
		Port:   8127,
		DBName: "vat_gst",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.vat-gst.events",
			"TAX_RULES_SERVICE_URL":  "http://127.0.0.1:8125",
		},
	},
	{
		Name:   "vendor-due-diligence-svc",
		Port:   8135,
		DBName: "vendor_due_diligence",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":        "http://127.0.0.1:8089",
			"COUNTERPARTY_SERVICE_URL": "http://127.0.0.1:8124",
			"KAFKA_EVENTS_TOPIC":       "zoiko.vendor-due-diligence.events",
		},
	},
	{
		Name:   "withholding-tax-svc",
		Port:   8216,
		DBName: "withholding_tax",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.withholding-tax.events",
			"TAX_RULES_SERVICE_URL":  "http://127.0.0.1:8125",
		},
	},
	{
		Name:   "workflow-history-svc",
		Port:   8097,
		DBName: "workflow_history",
		Env: map[string]string{
			"KAFKA_GROUP_ID": "workflow-history-svc",
			"KAFKA_TOPIC":    "zoiko.workflow.events",
		},
	},
	{
		Name:   "workflow-svc",
		Port:   8090,
		DBName: "workflow",
		Env: map[string]string{
			"AUTHORIZATION_SERVICE_URL": "http://127.0.0.1:8089",
			"KAFKA_EVENTS_TOPIC":        "zoiko.workflow.events",
			"KAFKA_GROUP_ID":            "workflow-svc",
		},
	},
	{
		Name:   "workforce-compliance-svc",
		Port:   8118,
		DBName: "workforce_compliance",
		Env: map[string]string{
			"AUTHZ_SERVICE_URL":      "http://127.0.0.1:8089",
			"EMPLOYEE_MASTER_URL":    "http://127.0.0.1:8108",
			"JURISDICTION_RULES_URL": "http://127.0.0.1:8082",
			"KAFKA_EVENTS_TOPIC":     "zoiko.compliance.events",
		},
	},
}

// generatedPages maps a console route to the services that route reads.
//
// Derived by walking app/admin/<area>/** and components/admin/<area>/** for
// @/lib/api/<module> imports, then resolving each module to the services it
// addresses: serviceUrl("alias"), const SERVICE = "alias", and the modules that
// read a ZOIKO_*_URL straight from the environment.
var generatedPages = map[string][]string{
	"/admin/access-control":    {"access-control-svc"},
	"/admin/ai-governance":     {"ai-governance-svc"},
	"/admin/audit-events":      {"audit-event-store-svc"},
	"/admin/commercial-ops":    {"purchase-order-svc", "purchase-request-svc", "spend-controls-svc", "vendor-due-diligence-svc"},
	"/admin/compliance":        {"anomaly-detection-svc", "compliance-risk-scoring-svc", "compliance-status-svc", "decision-support-svc", "exception-escalation-svc", "filing-tracker-svc"},
	"/admin/delegations":       {"delegated-authority-svc"},
	"/admin/documents":         {"document-vault-svc"},
	"/admin/evidence":          {"evidence-requirements-svc"},
	"/admin/finance":           {"accounts-payable-svc", "accounts-receivable-svc", "bank-reconciliation-svc", "financial-close-svc", "general-ledger-svc", "treasury-svc"},
	"/admin/governance":        {"governance-decision-log-svc"},
	"/admin/hr":                {"employee-master-svc", "leave-absence-svc", "org-structure-svc", "performance-review-svc", "workforce-compliance-svc"},
	"/admin/identity":          {"identity-context-svc"},
	"/admin/jurisdictions":     {"jurisdiction-rules-svc"},
	"/admin/legal":             {"board-resolutions-svc", "clause-template-svc", "contract-lifecycle-svc", "corporate-actions-svc", "counterparty-management-svc", "obligation-tracking-svc"},
	"/admin/notifications":     {"notification-svc"},
	"/admin/obligations":       {"jurisdiction-rules-svc", "obligations-svc"},
	"/admin/payroll":           {"benefits-svc", "compensation-svc", "payroll-exceptions-svc", "payroll-run-svc", "payroll-tax-svc"},
	"/admin/policies":          {"policy-svc"},
	"/admin/purchase-requests": {"purchase-request-svc"},
	"/admin/retention":         {"retention-registry-svc"},
	"/admin/schemas":           {"schema-registry-svc"},
	"/admin/secrets":           {"secret-vault-integration-svc"},
	"/admin/settings":          {"configuration-feature-flag-svc"},
	"/admin/tax":               {"corporate-tax-svc", "filing-preparation-svc", "tax-authority-interface-svc", "tax-determination-svc", "tax-rules-svc", "vat-gst-svc", "withholding-tax-svc"},
	"/admin/tenants":           {"tenant-entity-registry-svc"},
}
