package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// compilerVersion is stamped into compiled output provenance (§4.2).
const compilerVersion = "0.1.0"

func main() {
	mapPath := flag.String("map", "routing-map.yaml", "path to the GTRM routing map")
	regionsPath := flag.String("regions", "regions.yaml", "path to the region catalog")
	outPath := flag.String("out", "", "output path for compiled Traefik config (stdout if empty)")
	commit := flag.String("commit", "unknown", "commit SHA to stamp into provenance")
	requireProdSafe := flag.Bool("require-prod-safe", false, "reject generation from a non-prod map")
	check := flag.Bool("check", false, "drift check: compile and compare against --out; exit 1 on drift")
	flag.Parse()

	cat, err := loadRegions(*regionsPath)
	if err != nil {
		fatal("load regions: %v", err)
	}
	m, err := loadRoutingMap(*mapPath)
	if err != nil {
		fatal("load routing map: %v", err)
	}

	// Integrity gate: reject the whole map if any validation fails, emitting
	// every violation. No partial/among-invalid config is ever produced (§4.2).
	if errs := Validate(m, cat, *requireProdSafe); len(errs) > 0 {
		fmt.Fprintf(os.Stderr, "GTRM compile REJECTED — %d validation error(s):\n", len(errs))
		for _, e := range errs {
			fmt.Fprintf(os.Stderr, "  - %s\n", e)
		}
		os.Exit(1)
	}

	cfg := Emit(m, cat)

	body, err := yaml.Marshal(cfg)
	if err != nil {
		fatal("marshal traefik config: %v", err)
	}

	// Drift detection (§4.3, test I): compare freshly-compiled config against
	// the committed artefact at --out, ignoring the provenance header (its
	// timestamp/commit always differ). Drift means the map changed without a
	// recompile, or the compiled artefact was hand-edited — either way, block.
	if *check {
		if *outPath == "" {
			fatal("--check requires --out (the artefact to compare against)")
		}
		existing, err := os.ReadFile(*outPath)
		if err != nil {
			fatal("drift check: read %s: %v", *outPath, err)
		}
		if configBody(string(existing)) != string(body) {
			fmt.Fprintf(os.Stderr, "GTRM DRIFT DETECTED — %s does not match the compiled routing map.\n", *outPath)
			fmt.Fprintln(os.Stderr, "  The map changed without a recompile, or the artefact was hand-edited.")
			fmt.Fprintln(os.Stderr, "  Regenerate with the compiler and commit the result.")
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "GTRM drift check OK — %s matches the routing map.\n", *outPath)
		return
	}

	header := provenanceHeader(m, *commit, time.Now().UTC())
	out := append([]byte(header), body...)

	if *outPath == "" {
		_, _ = os.Stdout.Write(out)
	} else if err := os.WriteFile(*outPath, out, 0o644); err != nil {
		fatal("write output: %v", err)
	}

	fmt.Fprintf(os.Stderr, "GTRM compile OK — map_version=%d, %d tenant(s), %d router(s)\n",
		m.MapVersion, len(m.Tenants), len(cfg.HTTP.Routers))
}

// configBody strips the leading provenance comment block (comment/blank lines)
// so drift comparison ignores the always-changing timestamp/commit header.
func configBody(s string) string {
	lines := strings.Split(s, "\n")
	i := 0
	for i < len(lines) {
		t := strings.TrimSpace(lines[i])
		if t == "" || strings.HasPrefix(t, "#") {
			i++
			continue
		}
		break
	}
	return strings.Join(lines[i:], "\n")
}

func loadRegions(path string) (RegionCatalog, error) {
	var cat RegionCatalog
	b, err := os.ReadFile(path)
	if err != nil {
		return cat, err
	}
	if err := yaml.Unmarshal(b, &cat); err != nil {
		return cat, fmt.Errorf("parse yaml: %w", err)
	}
	return cat, nil
}

func loadRoutingMap(path string) (RoutingMap, error) {
	var m RoutingMap
	b, err := os.ReadFile(path)
	if err != nil {
		return m, err
	}
	if err := yaml.Unmarshal(b, &m); err != nil {
		return m, fmt.Errorf("parse yaml: %w", err)
	}
	return m, nil
}

// provenanceHeader stamps the compiled artefact so a deployed Traefik config
// can be traced back to the exact map + compiler that produced it (§4.2).
func provenanceHeader(m RoutingMap, commit string, at time.Time) string {
	return fmt.Sprintf(`# ─────────────────────────────────────────────────────────────────────────────
# GENERATED BY THE GTRM COMPILER — DO NOT HAND-EDIT.
# Source of truth: deployments/gtrm/routing-map.yaml (compile to regenerate).
# Hand edits are prohibited (decision doc §4.3) and detected by drift check.
#
#   map_version:      %d
#   compiler_version: %s
#   commit:           %s
#   generated_at:     %s
# ─────────────────────────────────────────────────────────────────────────────
`, m.MapVersion, compilerVersion, commit, at.Format(time.RFC3339))
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gtrm-compiler: "+format+"\n", args...)
	os.Exit(1)
}
