// Code generated by services/_contract/rollout.sh. DO NOT EDIT.
//
// Regenerate with: services/_contract/rollout.sh configuration-feature-flag-svc

package envelope

import (
	"net/http"
	"strings"
)

// ServicePolicy is this service's §4 conditional-field policy.
//
// The unconditionally mandatory fields — tenant_id, actor_subject_id,
// request_id, correlation_id, source_channel — and idempotency_key on material
// writes are enforced for every service and are not expressible here.
func ServicePolicy() Policy {
	return Policy{
		ServiceName: "configuration-feature-flag-svc",

		// §4: mandatory for entity-specific records (INV-02).
		LegalEntityID: NotRequired,

		// §4: required for governed sensitive access.
		PurposeContext: NotRequired,

		// This service does not post to an accounting book.
		BookID: NotRequired,

		// POST endpoints that resolve or evaluate and change nothing get the
		// full envelope except the idempotency_key, which the material-write
		// gate would otherwise demand for a read. A resolve/evaluate can be
		// repeated safely. Matches POST_READ in services/_contract/rollout.sh.
		MaterialWrite: func(r *http.Request) bool {
			switch {
			case r.URL.Path == "/v1/config/resolve":
				return false
			case strings.HasPrefix(r.URL.Path, "/v1/flags/") && strings.HasSuffix(r.URL.Path, "/evaluate"):
				return false
			}
			return defaultMaterialWrite(r)
		},
	}
}
