-- fiscal-calendar-svc (REF-04) -- tenant- and entity-scoped schema.
--
-- Every table carries tenant_id and FORCE ROW LEVEL SECURITY (see the policies
-- at the end of this file and in 000003/000004). Unlike the global reference
-- registries, a fiscal calendar belongs to ONE legal entity of ONE tenant.
--
-- WHAT IS DATA, WHAT IS CODE
--   The period pattern (months / 4-4-5 weeks / special periods), the fiscal-year
--   start, the week convention and the book/basis `scope` are DATA in these
--   tables. No country, jurisdiction or currency value appears in any
--   constraint below. The set of pattern TYPES is the service's code
--   vocabulary and is validated in the application, not here.
--
-- No hard delete anywhere (000002): a version is superseded, never removed.
--
-- btree_gist is a TRUSTED extension (PostgreSQL 13+): a role with CREATE on the
-- database can install it. If the migration role lacks that privilege, have a
-- superuser run `CREATE EXTENSION btree_gist;` once per database first.
CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE IF NOT EXISTS fiscal_calendars (
    calendar_id      UUID PRIMARY KEY,                      -- UUIDv7, generated by the service
    tenant_id        TEXT NOT NULL,
    legal_entity_id  TEXT NOT NULL,
    code             TEXT NOT NULL,                         -- tenant-chosen attribute, not identity
    scope            TEXT NOT NULL,                         -- opaque book/basis label; never interpreted here
    status           TEXT NOT NULL,
    version          BIGINT NOT NULL DEFAULT 1,
    created_by       TEXT NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    recorded_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT fiscal_calendars_status_known CHECK (status IN ('DRAFT', 'ACTIVE')),
    CONSTRAINT fiscal_calendars_code_shape CHECK (code ~ '^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$'),
    CONSTRAINT fiscal_calendars_scope_shape CHECK (scope ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$'),
    CONSTRAINT fiscal_calendars_version_positive CHECK (version >= 1),
    CONSTRAINT fiscal_calendars_code_unique UNIQUE (tenant_id, legal_entity_id, code),
    -- Target of the composite FK that keeps a version's denormalised
    -- tenant/entity/scope identical to its calendar's.
    CONSTRAINT fiscal_calendars_scope_key UNIQUE (calendar_id, tenant_id, legal_entity_id, scope)
);

CREATE TABLE IF NOT EXISTS fiscal_calendar_versions (
    version_id                UUID PRIMARY KEY,
    calendar_id               UUID NOT NULL,
    tenant_id                 TEXT NOT NULL,
    legal_entity_id           TEXT NOT NULL,
    scope                     TEXT NOT NULL,
    version_no                INTEGER NOT NULL,
    pattern                   JSONB NOT NULL,
    fiscal_year_start_month   SMALLINT NOT NULL,
    fiscal_year_start_day     SMALLINT NOT NULL,
    effective_from            DATE NOT NULL,
    effective_to              DATE,                         -- exclusive; NULL = open-ended
    status                    TEXT NOT NULL,
    proposed_by               TEXT NOT NULL,
    proposal_reason           TEXT NOT NULL,
    approved_by               TEXT,
    approval_reason           TEXT,
    approved_at               TIMESTAMPTZ,
    activated_by              TEXT,
    activated_at              TIMESTAMPTZ,
    superseded_by_version_id  UUID REFERENCES fiscal_calendar_versions (version_id),
    recorded_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                   BIGINT NOT NULL DEFAULT 1,
    CONSTRAINT fcv_calendar_fk FOREIGN KEY (calendar_id, tenant_id, legal_entity_id, scope)
        REFERENCES fiscal_calendars (calendar_id, tenant_id, legal_entity_id, scope),
    CONSTRAINT fcv_version_no_unique UNIQUE (calendar_id, version_no),
    CONSTRAINT fcv_status_known CHECK (status IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED')),
    CONSTRAINT fcv_version_no_positive CHECK (version_no >= 1),
    CONSTRAINT fcv_version_positive CHECK (version >= 1),
    CONSTRAINT fcv_pattern_is_object CHECK (jsonb_typeof(pattern) = 'object' AND pattern ? 'type'),
    CONSTRAINT fcv_start_month CHECK (fiscal_year_start_month BETWEEN 1 AND 12),
    CONSTRAINT fcv_start_day CHECK (fiscal_year_start_day BETWEEN 1 AND 28),
    CONSTRAINT fcv_effective_window CHECK (effective_to IS NULL OR effective_to > effective_from),
    -- Segregation of duties is also a database fact: nobody approves their own proposal.
    CONSTRAINT fcv_approved_has_independent_approver CHECK (
        status = 'DRAFT' OR (approved_by IS NOT NULL AND approved_by <> proposed_by AND approved_at IS NOT NULL)),
    CONSTRAINT fcv_in_force_has_activation CHECK (
        status IN ('DRAFT', 'APPROVED') OR (activated_by IS NOT NULL AND activated_at IS NOT NULL)),
    -- A superseded version always records where it ended and what replaced it.
    CONSTRAINT fcv_superseded_is_closed CHECK (
        (status = 'SUPERSEDED') = (superseded_by_version_id IS NOT NULL)
        AND (status <> 'SUPERSEDED' OR effective_to IS NOT NULL)),
    -- ONE in-force version per (tenant, entity, scope, effective interval).
    -- ACTIVE and SUPERSEDED both occupy their interval: a superseded version
    -- still governs the dates it was in force.
    CONSTRAINT fcv_one_in_force_per_interval EXCLUDE USING gist (
        tenant_id WITH =,
        legal_entity_id WITH =,
        scope WITH =,
        daterange(effective_from, effective_to, '[)') WITH &&
    ) WHERE (status IN ('ACTIVE', 'SUPERSEDED'))
);
CREATE INDEX IF NOT EXISTS idx_fcv_calendar ON fiscal_calendar_versions (calendar_id, version_no);
CREATE INDEX IF NOT EXISTS idx_fcv_scope_in_force ON fiscal_calendar_versions (tenant_id, legal_entity_id, scope, effective_from)
    WHERE status IN ('ACTIVE', 'SUPERSEDED');

CREATE TABLE IF NOT EXISTS calendar_transition_plans (
    plan_id                 UUID PRIMARY KEY,
    tenant_id               TEXT NOT NULL,
    legal_entity_id         TEXT NOT NULL,
    calendar_id             UUID NOT NULL REFERENCES fiscal_calendars (calendar_id),
    from_version_id         UUID NOT NULL REFERENCES fiscal_calendar_versions (version_id),
    to_version_id           UUID NOT NULL REFERENCES fiscal_calendar_versions (version_id),
    impact_assessment       JSONB NOT NULL,
    affects_posted_periods  BOOLEAN NOT NULL,
    mapping                 JSONB NOT NULL,                 -- {old period key: [new period keys]}
    status                  TEXT NOT NULL,
    proposed_by             TEXT NOT NULL,
    reason                  TEXT NOT NULL,
    decided_by              TEXT,
    decision_reason         TEXT,
    decided_at              TIMESTAMPTZ,
    version                 BIGINT NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ctp_status_known CHECK (status IN ('PROPOSED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ctp_moves CHECK (from_version_id <> to_version_id),
    CONSTRAINT ctp_version_positive CHECK (version >= 1),
    CONSTRAINT ctp_impact_is_object CHECK (jsonb_typeof(impact_assessment) = 'object'),
    CONSTRAINT ctp_mapping_is_object CHECK (jsonb_typeof(mapping) = 'object'),
    CONSTRAINT ctp_posted_needs_mapping CHECK (NOT affects_posted_periods OR mapping <> '{}'::jsonb),
    CONSTRAINT ctp_decided_consistent CHECK (
        (status = 'PROPOSED') = (decided_by IS NULL AND decided_at IS NULL)),
    CONSTRAINT ctp_approved_independent CHECK (status <> 'APPROVED' OR decided_by <> proposed_by)
);
-- One live (non-rejected) plan per target version.
CREATE UNIQUE INDEX IF NOT EXISTS ux_ctp_one_live_plan ON calendar_transition_plans (to_version_id) WHERE status <> 'REJECTED';
CREATE INDEX IF NOT EXISTS idx_ctp_calendar ON calendar_transition_plans (calendar_id);

-- Append-only lifecycle history: who moved which version, why, when.
CREATE TABLE IF NOT EXISTS fiscal_calendar_status_history (
    history_id         UUID PRIMARY KEY,
    tenant_id          TEXT NOT NULL,
    version_id         UUID NOT NULL REFERENCES fiscal_calendar_versions (version_id),
    from_status        TEXT,                                -- NULL on creation
    to_status          TEXT NOT NULL,
    actor              TEXT NOT NULL,
    reason             TEXT NOT NULL,
    recorded_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    resulting_version  BIGINT NOT NULL,
    correlation_id     TEXT,
    CONSTRAINT fcsh_known CHECK (
        (from_status IS NULL OR from_status IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED'))
        AND to_status IN ('DRAFT', 'APPROVED', 'ACTIVE', 'SUPERSEDED'))
);
CREATE INDEX IF NOT EXISTS idx_fcsh_version ON fiscal_calendar_status_history (version_id, recorded_at);

-- Row-level security: a tenant sees and writes only its own rows. FORCE makes
-- it apply to the table owner too. NULLIF because a pooled connection keeps a
-- custom GUC as '' after the transaction-local SET resets.
ALTER TABLE fiscal_calendars ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_calendars FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON fiscal_calendars FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));

ALTER TABLE fiscal_calendar_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_calendar_versions FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON fiscal_calendar_versions FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));

ALTER TABLE calendar_transition_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_transition_plans FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON calendar_transition_plans FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));

ALTER TABLE fiscal_calendar_status_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE fiscal_calendar_status_history FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_policy ON fiscal_calendar_status_history FOR ALL
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));
