// Code generated by services/_contract/rollout.sh. DO NOT EDIT.
//
// NOTE: written by hand for fiscal-calendar-svc because rollout.sh's service
// list has not been extended for this new service (see SPEC_DEVIATIONS.md).
// The shape is identical to what rollout.sh generates for sibling services.

package envelope

// ServicePolicy is this service's §4 conditional-field policy.
//
// The unconditionally mandatory fields — tenant_id, actor_subject_id,
// request_id, correlation_id, source_channel — and idempotency_key on material
// writes are enforced for every service and are not expressible here.
func ServicePolicy() Policy {
	return Policy{
		ServiceName: "fiscal-calendar-svc",

		// Fiscal calendars are entity-scoped records (spec section 3: legal_entity_id is mandatory for entity-specific records).
		LegalEntityID: Required,

		PurposeContext: NotRequired,

		// This service does not post to an accounting book.
		BookID: NotRequired,
	}
}
