-- Revert FORCE ROW LEVEL SECURITY (leave ENABLE and policies intact).

ALTER TABLE compensation_structures NO FORCE ROW LEVEL SECURITY;
ALTER TABLE wage_revisions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE bonus_grants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE salary_components NO FORCE ROW LEVEL SECURITY;
ALTER TABLE structure_components NO FORCE ROW LEVEL SECURITY;